### ISSUE TITLE
Stats for bytes written by capture not aligning with bytes read by materialization

### ISSUE THREAD

**Issue by williamhbaker** [estuary/flow#1048]
A capture writing to a collection which is then materialized will have different stats for "bytes written/read", even though the "docs written/read" are the same. From what I have seen the materialization stats are often much lower.

For an example, I have this capture which has written ~11 GB and ~20M docs to collection `whb-test-bucket`:
<img width="1438" alt="image" src="https://github.com/estuary/flow/assets/55118525/8889c51e-384e-4d3d-8f1b-1e1bd69b7ce4">

The stats for the collection match up:
<img width="1438" alt="image" src="https://github.com/estuary/flow/assets/55118525/df782e51-5d92-4de2-abe5-b8cff2b66018">

The stats for a materialization don't though; even though it has read the same number of documents it reports to have read far less data. This is a delta-updates materialization:
<img width="1438" alt="image" src="https://github.com/estuary/flow/assets/55118525/d4590537-3b57-4b53-8ba4-b17392380a2d">

The stats from `catalog_stats` for the materialization seem to pretty much align with the stats records in the stats journal for the materialization. Here's the entire stats journal, since this materialization finished in 2 transactions:

```json
{
  "_meta": {
    "uuid": "62bae234-f5ab-11ed-8401-670d0e14a995"
  },
  "shard": {
    "kind": "materialization",
    "name": "estuary/whb/snowflake-s3",
    "keyBegin": "00000000",
    "rClockBegin": "00000000"
  },
  "ts": "2023-05-18T18:39:56.298090895Z",
  "openSecondsTotal": 0.001237713,
  "txnCount": 1,
  "materialize": {
    "estuary/whb/synthdata8gb/whb-test-bucket": {
      "right": {
        "docsTotal": 14,
        "bytesTotal": 8381
      },
      "out": {
        "docsTotal": 14,
        "bytesTotal": 8367
      }
    }
  }
}
{
  "_meta": {
    "ack": true,
    "uuid": "62bae234-f5ab-11ed-8802-670d0e14a995"
  }
}
{
  "_meta": {
    "uuid": "62dccbcb-f5ab-11ed-8401-670d0e14a995"
  },
  "shard": {
    "kind": "materialization",
    "name": "estuary/whb/snowflake-s3",
    "keyBegin": "00000000",
    "rClockBegin": "00000000"
  },
  "ts": "2023-05-18T18:39:56.520339641Z",
  "openSecondsTotal": 767.458143031,
  "txnCount": 1,
  "materialize": {
    "estuary/whb/synthdata8gb/whb-test-bucket": {
      "right": {
        "docsTotal": 20199986,
        "bytesTotal": 2972606615
      },
      "out": {
        "docsTotal": 20199986,
        "bytesTotal": 2952406629
      }
    }
  }
}
{
  "_meta": {
    "ack": true,
    "uuid": "62dccbcb-f5ab-11ed-8802-670d0e14a995"
  }
}
```

The stats from the capture are attached:
[capture_stats.txt](https://github.com/estuary/flow/files/11510879/capture_stats.txt)

**Comment by dyaffe** [comment]
Good find @williamhbaker this seems important since it also affects how we bill

**Comment by williamhbaker** [comment]
This is now fixed
