### ISSUE TITLE
usage-based reporting & billing v2

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#1122]
We've updated our pricing to bill on a fine-grain metric of task usage over time. Previously we had been assessing a "maximum" number of tasks in use over a month and billing on that measure. We're also formalizing a flexible tier-based pricing mechanism over data processing and task usage, and need to further account for any recurring service fees and one-off adjustments.

 To switch over, we must:

* [x] Produce stat events which sample fine-grain task & connector uptime.
* [x] Update reporting to roll up task usage to our hourly/daily/monthly grains.
* [x] Enhance the tenant model to represent pricing tiers and any recurring cost.
* [x] Model an auditable table of billing adjustments for make-goods and other one-off uses.
* [x] New billing report to apply tiers, recurring cost, and adjustments.
* [x] Work up a production migration for ☝️
* [x] Update UI to use the new report as-of 2023-08-01

**Comment by dyaffe** [comment]
Lets try to make the simplest UI changes possible right now to use what we currently have.   That would mean doing the following:

Update billing text from "The cloud tier includes two tasks and 10GB every month.  Thereafter you pay..."  to the following:

1.  If they have a credit card in: "Cloud tier."
2. If they don't have a credit card in: "The free tier lets you try Flow with up to 2 tasks and 10GB per month without entering credit card.  If you go beyond that, you'll have a 30 day free trial starting then."

Update "Tasks" in recent history to "Task Usage" and add "Hours" to label the amount in the row.

Update "Tasks by Month" to "Task Hours by Month"

Remove "included vs billed from both the task hours by month and the data volume by month graphs.
