### ISSUE TITLE
Binding Behavior Updates

### ISSUE THREAD

**Issue by williamhbaker** [estuary/flow#1276]
Discussed in #1219

These changes enable bindings for captures, derivations, and materializations to work in a consistent way with respect to "resetting" the state of a binding and re-starting its backfill when a binding is removed from a spec, as well as adding capabilities for a binding to be "reset" without removing it from the spec via a new `backfillVersion` property. Additionally, they will allow materializations to drop & re-create the respective materialized table (or equivalent) when a materialization binding is reset.

- [x] New `backfillVersion` and `bindingKey` concepts:
  - [x] Add `backfillVersion` to capture/derivation/materialization spec and `bindingKey` to protocol
  - [x] ~Implement automatic pruning of driver & runtime checkpoints for `bindingKey`'s that are removed from task specs~
- [x] Captures: Use `bindingKey` for keying binding state (depends on spec updates, above)
- [x] ~Graceful shutdown of connectors:~
  - [x] ~Make `connector-init` propagate shutdown signals to connectors and give them a chance to exit gracefully~
  - [x] ~Update materializations to clean up after themselves when signaled to exit (related: https://github.com/estuary/connectors/issues/984) - for this scope of work, most relevant for those that track column-like type information and produce constraints for existing tables~
- [x] Materializations drop & re-create tables (depends on graceful shutdown of connectors, above):
  - [x] ~Update "activate" logic to disable materialization shards before applying changes (when needed), and re-enable them after changes have been applied~
  - [x] Make materializations drop tables that were previously being materialized when the target tables have a different `bindingKey`
- [x] Add temporary migration shim which populates `state_key` on behalf of connectors even for captures / materializations built without it.
- [ ] Enforce that `backfill` counters are always monotonically increasing in the control plane
- [x] Use "asynchronous", runtime-driven strategy for `Apply` operations

**Comment by jgraettinger** [comment]
https://github.com/estuary/flow/pull/1292 is up with implementation for backfill counters and threading through a persistent `state_key` for connector use.

> Implement automatic pruning of driver & runtime checkpoints for bindingKey's that are removed from task specs

I did not implement this part yet (though it doesn't seem strictly required to move this feature forward)
