### ISSUE TITLE
More limitations on serialized document complexity

### ISSUE THREAD

**Issue by psFried** [estuary/flow#1296]
When materializing, we need to respect the limits imposed by destination systems, which may be more restrictive than Flow's own limits. For example, some systems have limits on the number of items in a JSON array, or the number of properties in an object. The ultimate goal is to respect those limits on a system-by-system (i.e. connector-by-connector) basis.

Some immediate questions that come up:

- What types of limits do we wish to put in place?
    - Array length?
    - Object properties?
    - String length? Truncate, or replace the string with a sentinel?
- It might be nice to avoid adding this to the materialize protocol until we have more confidence about how to model these limits. Is there a way to do that without unintentionally applying limits to systems that don't need them?
- What kind of logging would we like to see when these limits modify documents? Or should we try to leave sentinel values?
    - Or we could try adding something under `_meta` that describes which limits were applied, though that could also be tricky if we're trying to limit the overall size of the document, since it would then add to it.

**Comment by dyaffe** [comment]
I don't think that Johnny or I will have true answers for you here.  What I can say is that we've seen problems with certain data sets where they have quite a lot small fields that are nested -- each specific field may be relatively small, but together they go over Snowflake's or Redshifts limits.

My ideal solution here would be to add a total size for objects at any level and truncate above that.  Snowflakes limit is 16 MB and Redshift's is 2 MB, so something like 512 KB for any first level object and 256 for second level could make sense.

**Comment by psFried** [comment]
When we last discussed this, we decided to focus on just what's needed the use case at hand. At the time, we thought that use case was mainly just impacted by huge arrays, so that was the only thing we'd need to address. But I did some investigation and found some examples of documents that don't just have large arrays. They also have huge and deeply nested objects.

I hacked up an enhanced `SerPolicy` that's able to limit both array and object sizes, and have been testing a selection large json documents with various limits. I've confirmed that limiting array sizes (even as low as 50 elements) is not enough to get the total document size down. We need to limit the number of object keys, too.

I did some quick and dirty tests by sampling a selection of the largest documents and running them through `flowctl raw combine` using various `SerPolicy` parameters. I then determined the final serialized size of each document and output a list of the top 10 largest sizes among the output documents. Here's some preliminary results:

```
----
SerPolicy:
        str_truncate_after: 1 << 16,
        array_truncate_after: 1000,
        obj_truncate_after: 1000,

TopN(bytes):
6401008
6449382
6449644
6453070
7204711
7204951
7374555
7404059
7492833
11648436

----
SerPolicy:
        str_truncate_after: 1 << 16,
        array_truncate_after: 400,
        obj_truncate_after: 400,

TopN(bytes):
3320823
3320979
3333806
3432706
3432732
4299597
4317491
4346889
4527804
5727017

----
SerPolicy:
str_truncate_after: 1 << 16,
array_truncate_after: usize::MAX,
obj_truncate_after: 200,

TopN(bytes):
3181240
3405675
3813437
4257562
4288557
4322818
4337481
5705005
6572387
7786301

----
SerPolicy:
        str_truncate_after: 1 << 16,
        array_truncate_after: 200,
        obj_truncate_after: 400,

TopN(bytes):

3291327
3291483
3304617
3411324
3411348
4182477
4189315
4205890
4235397
5696010

----
SerPolicy:
        str_truncate_after: 1 << 16,
        array_truncate_after: 50,
        obj_truncate_after: usize::MAX,

TopN(bytes):
6412973
6413235
6416633
6463245
7167129
7167419
7230857
7262143
7381514
22762786
```

At this point, it seems like limiting both objects and arrays to 1000 elements would probably do the trick. I can work on validating whether that's the case.
