### ISSUE TITLE
Implement: work required for Google partner program

### ISSUE THREAD

**Issue by jshearer** [estuary/flow#1339]
-   They click "sign up with Estuary" in GCP marketplace
-   They're redirected to our signup page where they do the user and tenant registration like usual, and their tenant is linked to their google account
    -   At this point we'll store the google procurement ID on their tenant row, and set them to the google marketplace billing provider
-   Then they'll go into Google and sign up for the subscription, which will send a pub/sub message. We'll have something listening to pub/sub
    -   If we get `ENTITLEMENT_CREATION_REQUESTED`, we'll auto-approve by calling a google API
    -   After approval, we'll get a `ENTITLEMENT_ACTIVE` event, and only at *that* point should we treat the subscription as active
-   They can also do a bunch of other things to their entitlements
    -   `ENTITLEMENT_PLAN_CHANGE_REQUESTED` when they want to change plans (which they won't be able to do if we only have 1 subscription?), which we can either allow or not
    -   `ENTITLEMENT_PLAN_CHANGED` when an approval to the `CHANGE_REQUESTED` message goes through, to actually update their account in our system
    -   `ENTITLEMENT_PLAN_CHANGE_CANCELED` if they cancel the change request
    -   `ENTITLEMENT_PENDING_CANCELLATION` when they try to cancel
    -   `ENTITLEMENT_CANCELLED` after we approve the cancellation
    -   `ENTITLEMENT_DELETED` when the entitlement is actually gone and we should de-provision their account

These are the docs I found: https://cloud.google.com/marketplace/docs/partners/integrated-saas

**Comment by jgraettinger** [comment]
Done
