### ISSUE TITLE
Update auto-discovery settings UX in capture workflows

### ISSUE THREAD

**Issue by kiahna-tucker** [estuary/flow#1348]
**Last Updated:** Jan. 23, 2024

<hr />

Below are the base requirements for this feature:

* Allow `evolveIncompatibleCollections` to be set independently of the `addNewBindings` auto-discovery property.

**Comment by dyaffe** [comment]
@psFried is that possible to do only on new captures?

**Comment by psFried** [comment]
> @psFried is that possible to do only on new captures?

Yes, the new default will only affect new captures, and existing ones will continue to use their current values.
