### ISSUE TITLE
design: online shard splits

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#15]
# Shard Ranges and Online Splits

## Overview

Flow derivations and materializations process as Gazette [Shards], and use [recovery logs]
for durable storage of transactional states (derivation registers and corresponding consumption
states & acknowledgement intents -- see Gazette [exactly once] architecture). Recovery logs
ensure that Flow transactions are durable. They also enable "hot standby" secondary shard
assignments which live-tail the log and can quickly take over processing for a failed
primary assignment.

A single derivation or materialization may need to scale to many shards, with state storage
and processing work evenly divided between them. The handling for this scale-out requirement
in other systems is to force the user to pick a number of physical partitions up-front,
leading to the [Tyranny of Partitioning].

[shards]: https://gazette.readthedocs.io/en/latest/consumers-concepts.html#shards
[recovery logs]: https://gazette.readthedocs.io/en/latest/consumers-concepts.html#recovery-logs
[exactly once]: https://gazette.readthedocs.io/en/latest/architecture-exactly-once.html
[tyranny of partitioning]: https://estuary.readthedocs.io/en/latest/docs/how-flow-helps.html#tyranny-of-partitioning

## Breaking the Tyranny of Partitioning

Rather than requiring that the user declare a number of partitions up-front,
Flow derivations and materializations always begin processing with a single shard --
a shard which may be progressively sub-divided ("split") into more and smaller shards
at any time, as needed, and without downtime. Decisions to split a shard can be automated,
informed by current operational metrics such as CPU and disk usage.

Flow relies on two key implementation properties which enable these splits:

1. All Flow reads are "shuffled" reads: every shard _effectively_ reads all input physical
   partitions to identify instances of its assigned keys. Crucially, this decouples the
   1:1 correspondence of input partitions to "tasks" seen in other systems. A physical
   partition may be added at any time, and relevant Flow shards will immediately begin
   reading it.

    Of course, having all shards _actually_ read every partition would be pretty inefficient.
    In practice shards work together to perform in-memory coordinated reads of each
    partition in order to minimize data movement, while maintaining the effective semantics
    of every shard reading every partition.

2. Recovery logs -- as Gazette journals -- persist their data as files in cloud storage, and recovery
   consists of identifying & pulling down portions which must be "re-played" to produce a desired
   on disk state. Importantly, this makes recovery logs cheap to "fork" since no movement of
   physical data need occur. Instead, a fork copies metadata from the parent log and thereafter
   maintains its own and separate lineage, while continuing to reference shared historical data
   segments.

## RangeSpecs

Every Flow shard has a [RangeSpec] which identifies its "owned" ranges of responsibility.
These ranges are on two axes:

[rangespec]: https://github.com/estuary/flow/blob/master/go/protocols/flow/flow.proto#L218

-   The range of document keys which this shard must read and possibly index.
    -   For derivation shards, "update" lambdas are _only_ invoked if the key falls within the shard's range.
    -   For materialization shards, the shard has unique ownership and responsibility for materialization of collection documents within key range.
-   The range of "rotated" document UUID clocks.
    -   For derivation shards, "publish" lambdas are _only_ invoked if **both** the key and r-clock are within the shard's range.

Ranges operate over the sorted and un-hashed key space, which co-locates similar keys and
enables shards to maintain a sorted index over its assigned keys.

Rotated clocks are an advanced feature, but enable an important scaling capability unique to Flow:
Suppose we must left-join a low volume event stream (e.x. updates to a product catalog),
with a high-volume stream (e.x. views of product pages) on a shared key (e.x. product ID).
We _index_ product profiles as derivation registers, and _join_ each page view on product ID
to derive the view enriched with its last-indexed product profile.

Further suppose that keys aren't well distributed (e.x., some products have far more & faster
views than others), and the distribution changes over time (e.x. a popular product) --
some product IDs may produce a disproportionate and even overwhelming share of views.

With key-based scaling (only), we can subdivide on product IDs into smaller and smaller shards,
but a shard must still process _all_ matched products of the high-volume stream, which
may overwhelm it and will certainly produce resource imbalances with respect to other,
lower-volume product IDs.

A better option is to instead index each product ID with _multiple_ shards,
and then pick _one_ of those shards arbitrarily to process a given page view,
so that shards even balance the query workload.
Range "r-clocks" enable exactly this form of scale-out: document clocks -- already embedded
in each document UUID -- are mined as a source of deterministic, repeatable entropy to
produce a pseudo random selection of a processing shard.

### Split API

Shards offer an API through which they may be asked to split themselves into two (either on key, or on rotated clock).
On invocation, the API first identifies an appropriate subdivision of the key or clock space.
The exact means by which that is done is flexible and likely to change over time:

-   If splitting on key and database size is the primary split criteria (e.x. derivation updates),
    it may introspect RocksDB to determine an approximate median key.
-   Or, if splitting on key and CPU time is the primary split criteria (e.x. materialization),
    it may uses a running reservoir sample to pick an approximate median.
-   Or, if splitting on r-clock, it picks half way through the current r-clock range
    (r-clocks are a uniform, continuous distribution).

Whatever the means, the API will identify _two_ child RangeSpecs which collectively
cover the shard's current (parent) RangeSpec. By construction, one child will share
the beginning range values for both key & r-clock of the parent: call this the
"left-hand" child, and the other the "right-hand" child.

These RangeSpecs fully qualify the shard IDs of the left- and right-hand children,
as shard IDs are named by `{Task}/{range.KeyBegin}/{range.RClockBegin}`, where `Task`
is the derivation or materialization name. This naming means the left-hand child will
re-use the shard of the parent, while the right-hand child maps into a new shard.

The API then, as a single shard Apply RPC (and Etcd transaction):

-   Updates its ShardSpec adding label `estuary.dev/splitting-into: ${right_hand_shard_id}`.
-   Creates a _new_ RHS ShardSpec with label `estuary.dev/splitting-from: ${left_hand_shard_id}`.
    The ShardSpec is initialized without hot standbys, such that the shard is assigned to a single process.

Once the `estuary.dev/splitting-into` label is set on a ShardSpec, the Split API will refuse
further attempts to split the shard until it is removed (e.x. upon split completion).

The API invocation then completes, and the parent shard continues processing as per usual.

### Shard Initialization

The newly created RHS ShardSpec is assigned to a process and begins recovery.

It creates is recovery log journal if it doesn't yet exist.

It discovers its splitting status from the `estuary.dev/splitting-from` label,
and rather than beginning recovery log playback from it's _own_ recovery log,
it instead fetches the `recoverylog.FSMHints` of its identified `splitting-from`
parent shard and recovers _those_. This could take a while, as the shard catches
up to the parent's recovery log head.

At this point, note there are three shard assignments involved:

-   **P**: The running parent primary shard assignment, whose Split API initiated the split operation.
    This assignment continues to actively process transactions under its (the parent) RangeSpec.
-   **LHS**: The hot-standby of the parent primary, which is live-tailing the parent but will become the LHS child shard.
-   **RHS**: The newly-created RHS child, which is catching up to the parent **P**.

### Shard Cut-over

Eventually, the **RHS** shard completes log playback and performs the usual transactional,
write-fenced handoff of log ownership from **P**.

`recoverylog.Player` produces a final set of `recoverylog.FSMHints` which detail the exact
segments of the parent / LHS log. The RHS updates these FSMHints to reflect its new RHS
recovery log, while leaving former segments in place and referencing the LHS log.

At this moment:

-   **P** is (presumably) still running, but has been fenced from the LHS recovery log and cannot commit write further transactions.
-   **LHS** is (presumably) still tailing the LHS log, but has not been promoted to primary.
-   **RHS** has ownership of the LHS log, but has yet to begin processing transactions.

This moment is the point-in-time at which the effective "split" is performed.

Note it's _possible_ that **P** was re-assigned while RHS was acquiring log ownership:
**LHS** may have been promoted to primary, it may have performed a transactional hand-off which
in turn fenced **RHS** from the log, and may have processed another transaction under its
still-current (parent) RangeSpec.

Were this to have happened, it would invalidate this moment as a split-point, since another
effective parent transaction has processed which LHS would see but RHS would not. We must
guard to ensure that this has not happened.

As an aside, it's also possible that **RHS** was re-assigned and we are a current zombie.
There may be a new RHS assignment which could in theory have completed recovery and fenced
the former **RHS** from the log. This case doesn't invalidate this split point,
as it's still the case that further parent transactions have not processed.

To finalize the cut-over, the RHS shard performs an Etcd transaction which:

-   Verifies the continued assignments of **P** and **RHS**.
    This guards against the race detailed above: if **P** is still primary,
    **LHS** _cannot_ have been promoted, and further transactions _cannot_ have processed.
    The **RHS** check is included for completeness.

-   Writes its FSMHints as its primary hints. This ensures a future RHS assignment will reliably
    recover this snapshot should it crash immediately after this Etcd transaction commits.

-   Updates the **P** ShardSpec to remove the `estuary.dev/splitting-into` label and update
    its RangeSpec to reflect its new left-hand child status.

-   Updates its **RHS** ShardSpec to remove the `estuary.dev/splitting-from` label.

-   Removes the **P** assignment.

Upon Etcd transaction commit, shard cut-over has completed. With the **P** assignment removed,
it will shut down and **LHS** will promote to primary under its new left-hand RangeSpec.
This is fast, as **LHS** was already tailing its recovery log. The **RHS** shard can immediately
begin processing transactions.

If -- on the other hand -- the Etcd transaction fails due to conflict, then this split point is
invalidated. The **RHS** shard removes its assignment from Etcd and returns an error. A new **RHS**
will be assigned and will make another attempt to perform a cut-over.

**Comment by psFried** [comment]
Great write up! I feel like this is all on the right path, but I haven't quite proved to myself that the shard cut-over is 100% correct (not that I see anything _wrong_, just that I'm still working on coming to a good enough understanding). ...

> P is (presumably) still running, but has been fenced from the LHS recovery log and cannot commit write further transactions.

What causes **P** to be fenced and unable to commit? Is this due to the "write-fenced handoff of log ownership from **P**"?

**Comment by jgraettinger** [comment]
Yep. There actually _two_ mechanisms which assure this:

The older, though still valid mechanism is [recoverylog.FSM](https://pkg.go.dev/go.gazette.dev/core/consumer/recoverylog#FSM), a state machine over recorded log operations which enforces strict lineage of applied operations. During hand-off, a recovering LHS injects a no-op recorded operation whose only purpose is to wrest control of the lineage from the recorder P, such that all other readers of the log must agree with LHS's ongoing operation lineage.

This works just fine, but could now be considered an assertion / sanity check which supplements the newer primary mechanism,
which is journal registers: See [here](https://gazette.readthedocs.io/en/latest/architecture-transactional-appends.html#statevalidatepreconditions) and [here](https://pkg.go.dev/go.gazette.dev/core@v0.88.0/broker/protocol#AppendRequest)

**Comment by psFried** [comment]
I really like that it uses only etcd and existing mechanisms for storing all the relevant state.
My impression is that this comes with the constraint that a given shard can only split into exactly 2 child shards (at a time). I don't think that would pose a problem, but I do think it's worth talking through.

My original reaction was to wonder about the implications of only being able to scale by dividing by two. Does that mean that we could only have a power of two shards if we want the division of the `rclock` space to be even? If so, it implies that we'd need to coordinate multiple separate shard splits in order to go from, say, 4 to 8 shards. It might we worth trying to roughly sketch that out if it is indeed required.

I think it can only split into two because the **RHS** is the one and only coordinator, and it presumably identifies itself as such because it has a `splitting-from` label and its `rclock` range start is different from that of its parent. But it occurs to me that the shard splitting API could possibly split a single shard into more than one child and explicitly mark one of them to be the "coordinator". And that a handoff from **P** to _many_ **LHS** shards could theoretically work the same way as it does to one **LHS** shard. Anyway, it's possible that there's a path here to be able to split a shard into more than 2 children, but I won't try to shave that yak right now. Probably a good time to pause and get your reaction before I go too far down that road.

**Comment by jgraettinger** [comment]
| Does that mean that we could only have a power of two shards if we want the division of the rclock space to be even?

That's right. Shard splits always form a binary tree. R-clock splits are always at a midpoint, and key splits can be anywhere (but ideally at a median). Crucially, different portions of the tree can be at different depths -- if I want to index on ordered timestamps, for example, I'll probably need to keep on splitting the right-most node of the tree while leaving its left sibling at depth = 1.

| I think it can only split into two because the RHS is the one and only coordinator,

The criteria are that there _must_ be a moment (a "split point" as I call it above) where there's:

  1) A fenced owner of the _parent_ recovery log AND
  2) A certainty that there are no ongoing log commits which could race an Etcd transaction effecting the cut-over.

There's a natural time where this happens, in the moment immediately after shard recovery but before transaction processing has begun, which we're taking advantage of here. The other nice property of doing it as part of recovery is that it simplifies answers around "what happens if I crash part way through splitting ?" -- simple! your successor tries again on _its_ recovery.

Now, during this moment, we certainly could have it also create children 3,4, ... N > 2. It would involve downtime for those children N > 2 -- child 0 (LHS) has a hot standby ready to take over, and child 1 (RHS) can continue processing with it's current recovered store, but children 2, 3... N must do a cold-start recovery.

|  it implies that we'd need to coordinate multiple separate shard splits in order to go from, say, 4 to 8 shards

The decision to split a given node is independent from any other -- we aren't constrained to say we must go from 4 -> 8. Even if splitting on r-clock, I might go to 5 or 6 simply because some shards happen to currently be assigned to faster hardware and don't need it -- and that's ok!

Of course the ultimate decision maker is intended to be a monitoring control loop, not a human operator. That control loop is simpler to reason about if it only does N=2 splits, vs its also having to pick a suitable value of N. And it doesn't mind the tedium of walking a bunch of progressive splits from 1 => 16, say.

My final reason for keeping it at power-of-two splits is that bugs in the split mechanism will be _painful_, causing pagers to go off and waking people at night. We want as little complexity and surface area here as possible.

**Comment by jgraettinger** [comment]
I'm closing this as I believe, barring new learnings / feeback, design work is mostly wrapped and it's on to implementation.
