### ISSUE TITLE
materializations: filter reserved SQL keywords for DBs

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#174]
We have a [pretty naïve](https://github.com/estuary/flow/blob/master/go/materialize/driver/sql2/spec_mapping.go#L22-L29) approach for determining whether an identifier must be quoted for SQL.

It currently breaks on properties like 'from' which can reasonably be part of user JSON schemas, causing us to attempt to apply SQL DDL which fails with an error.

We should update the `sql2` package to support a reserved keyword list specific to the database at hand, which is checked when making identifier quoting decisions.

**Comment by jgraettinger** [comment]
Done (PRs in connectors repo)

**Comment by mdibaiee** [comment]
For the record: https://github.com/estuary/connectors/pull/171
https://github.com/estuary/connectors/pull/170
