### ISSUE TITLE
Extra typescript files should not cause catalog builds to fail

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#180]
Currently extra typescript files cause catalog builds to fail.  We should update to ignore unrelated typescript files in the build linter.

**Comment by psFried** [comment]
It seems that @jgraettinger already fixed this in b55259ab but it's possible that you might still run into the issue if you have an old `package.json` file sitting around. @dyaffe do you remember which project you were in when you encountered this? If so, then we can verify that it's just an old `package.json` by checking if the `lint` script passes `**/*.ts`. If it does, then it's old, and you can just delete `package.json` and it will get regenerated when you run `flowctl` next.
