### ISSUE TITLE
Updates for AWS S3 Connector Defaults

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#181]
We need to make a few updates to the AWS S3 connector to make it work out of the box:

1.  Amazon expects ascendingKeys: false vs ""
2. awsAccessKeyId and awsSecretAccessKey should not be required for public datasets
3. Add an example of "us-east-1" to region to make it obvious what most would be

**Comment by psFried** [comment]
This is resolved by #184 and (https://github.com/estuary/connectors/pull/18)
