### ISSUE TITLE
packaging: provide `flowctl.sh` wrapper for flowctl in docker for onboarding 

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#204]
As a new new or prospective user, I'd like a really easy path for grabbing a recent Flow release (as a `flowctl` binary) which:

 - [ ] Is likely to work in my arbitrary amd64 linux environment.
 - [ ] Automatically downloads / caches an `etcd` binary (into `/tmp` ?).
 - [ ] Packages `gazctl` subcommands within the binary (along with `serve gazette` ?).
 - [ ] Is published as an artifact of CI release builds.

**Comment by jgraettinger** [comment]
[Link to existing](https://github.com/estuary/flow/blob/master/go/flowctl/cmd-test.go#L205) way in which Etcd is invoked from `flowctl test` and `flowctl develop`.

**Comment by snowzach** [comment]
It seems like the easiest path forward is to publish a wrapper script that will run flowctl in docker. I've been working on it here #213 and it's now working on MacOS as well with M1 support. Perhaps I can see about adding gazctl and port 8080 support as well.
