### ISSUE TITLE
Transition to github workflow for docs

### ISSUE THREAD

**Issue by oliviamiannone** [estuary/flow#205]
We've seen limitations to the gitbooks doc framework. 
- Issues with version control, merging, and responsiveness while editing
- Inability to create dynamically updated documentation of commands, as in the [gazette docs](https://gazette.readthedocs.io/en/latest/reference-gazctl.html)
- Inability to re-use content blocks across pages. 

Porting the documentation to a github-based system should resolve these issues and make the system more robust when we have more authors in the future.

**Comment by jgraettinger** [comment]
Done
