### ISSUE TITLE
Technical review for Kafka blog post

### ISSUE THREAD

**Issue by oliviamiannone** [estuary/flow#215]
https://docs.google.com/document/d/1vu7MB3bALCPoIynjkXpbpssbhIhyUHWP8nkmfw6PWPY/edit?usp=sharing

This post needs review for technical accuracy of its existing (relatively high-level) content. 

Also, it should be evaluated to see if a greater level of technical detail is warranted. If so, we can collaborate to add those additional details.

**Comment by snowzach** [comment]
Hey @saterus do you have time to check this out? I don't really have enough operational knowledge of Kafka to comment intelligently. I've used it but not maintained it or dealt in depth with many of it's pain points.
