### ISSUE TITLE
snowflake: two unexpected connector errors

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#238]
First error:

```
runTransactions: store.StartCommit: combine.Finish: driver implementation error: loaded key () was not requested by Flow in this transaction (document {\"_meta\":{\"uuid\":\"20f80293-1183-11ec-b401-6ff6c75d8fa5\"},
```

Second error:

```
completeRecovery: store.RestoreCheckpoint: reading Opened: installing fence: incrementing fence: 000630 (57014): Statement reached its statement or warehouse timeout of 300 second(s) and was canceled.
```

**Comment by jgraettinger** [comment]
Managed to get a reproduction of the timeout error!

Methodology is to run the containerized snowflake connector materializing citi-bike data from S3, where the connector is further modified to log and sleep for 15 seconds immediately prior to issuing a commit (after the fence check and table updates have been issued to the transaction).

Then run with `flowctl develop`, and `kill -9` the snowflake `connector` process within that instrumented sleep, in order to uncleanly abort a running session that's holding a transaction lock within the database.

Then start up `flowctl develop` again. I observe that the restarted connector is attempting to update the fence, but it's `UPDATE` shows up as "blocked" in the snowflake UI.

**Comment by psFried** [comment]
Seems like maybe it just takes a few minutes for the lock Interesting that it took over 5 minutes to complete, though. Do you have a sense of what specific timeout that's waiting on? Is it maybe waiting for the old session to timeout?

**Comment by jgraettinger** [comment]
Not yet. I'm going through `SHOW PARAMETERS` but so far nothing leaps out. It's clear there _is_ a fixed timer value: a second run took 5m46s vs 5m45s

**Comment by psFried** [comment]
I just found [this page in the Snowflake docs](https://docs.snowflake.com/en/sql-reference/parameters.html#abort-detached-query) which says that queries are aborted 5 minutes _after_ the session dies. This may explain what's going on. If the previous session dies, but the effective `STATEMENT_TIMEOUT_IN_SECONDS` is relatively short, then the statement from the new session may not complete before the statements from the old session expire.

**Comment by jgraettinger** [comment]
Bingo! [From these docs ](https://docs.snowflake.com/en/sql-reference/transactions.html#aborting-transactions):

> 
> If a transaction is running in a session and the session disconnects abruptly, preventing the transaction from committing or rolling back, the transaction is left in a detached state, including any locks that the transaction is holding on resources. If this happens, you might need to abort the transaction.
> 
> To abort a running transaction, the user who started the transaction or an account administrator can call the system function, SYSTEM$ABORT_TRANSACTION.
> 
> If the transaction is not aborted by the user:
> 
> If it blocks another transaction from acquiring a lock on the same table and is idle for 5 minutes, it is automatically aborted and rolled back.
> 
> If it does not block other transactions from modifying the same table and is older than 4 hours, it is automatically aborted and rolled back.

**Comment by jgraettinger** [comment]
Given our inability to re-produce the first error, I think the remaining goal before closing out this issue is to land reasonable always-on checks & instrumentation to best pinpoint this if it ever happens again, and move on. Sound good?

**Comment by psFried** [comment]
> Given our inability to re-produce the first error, I think the remaining goal before closing out this issue is to land reasonable always-on checks & instrumentation to best pinpoint this if it ever happens again, and move on. Sound good?

Yeah, I think that sounds like a good plan. I feel pretty good about merging the instrumentation that's added in #240, and I think that would be sufficient for this purpose. If that sounds good to you, I can just merge it up and close this for now.

**Comment by jgraettinger** [comment]
We've resolved the timeout issue, and taken the `loaded key ()` error as far as we can, with new instrumentation if it re-occurs.
