### ISSUE TITLE
models: catalog as source-of-truth for JournalSpecs and ShardSpecs

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#250]
A while back, we knew there were important knobs in JournalSpecs and ShardSpecs (in theory -- we never fully wired them up), but we didn't want to thread them through Flow data models and punted by introducing the JournalRules / ShardRules mechanism.

Meanwhile it's currently ambiguous what the source-of-truth is for a running Journal or ShardSpec in the system. Is it the extant JournalSpec ? The spec which would exist once applying JournalRules ? We've opted to directly edit resources as required to do things we need.

Lately there are new, important performance knobs in ShardSpecs:

  * `ring_buffer_size` gazette/core#304
  * `read_channel_size` gazette/core#305

These are values which really ought to be managed in the catalog, but I groan at the idea of powering them through ShardRules & threading that up. I think we want to:

* Deprecate JournalRules / ShardRules
* Introduce a catalog `commonStorage` stanza which may only be present in the root catalog yaml, and which defines shared configuration for where to store journal fragments
* Allow individual collections to override some or all of the fields of that stanza
* Allow catalog tasks to define important knobs like `ring_buffer_size` / `read_channel_size`.
* Support labels within catalog tasks (finally).

The desired end state is that JournalSpecs / ShardSpecs are fully defined, modeled, and updated by their owning CatalogTasks.

When applying a built catalog to etcd:
 * We upsert updated CatalogTasks, obtaining a modification revision
 * We converge associated shards to the task's state, and set a new modification-revision label in the ShardSpec (task created-at is already present).
 * We converge associated journals (also setting a modification-revision ?).

To power hot-reload, rather than watching the catalog keyspace for changed CatalogTasks, we instead watch for changes to the ShardSpec which change the modification-revision. On seeing one we drain reads as we do today.

**Comment by jgraettinger** [comment]
> * Introduce a catalog commonStorage stanza which may only be present in the root catalog yaml, and which defines shared configuration for where to store journal fragments
> * Allow individual collections to override some or all of the fields of that stanza

Having given this more thought,  this appears a) challenging to define and understand reasonable semantics in the face of catalog imports (which `commonStorage` applies?), and b) _mostly_ duplicative with what can be accomplished using YAML anchors / aliases / merge `<<` keys.

I'd like to see what it looks like if we require that journal and shard configuration be explicit on each catalog entity, but define defaults such that `flowctl test` and `flowctl develop` will let you proceed without filling out those details quite yet.

**Comment by psFried** [comment]
Using yaml anchors might be difficult when tasks are defined within different yaml files. I feel like perhaps instead of `commonStorage`, we should consider having named `storage` entities, which can be referenced by collections. It would more naturally fit into an AuthZ model if storage locations could be named, and we could then have collections all reference a storage entity called `default` unless overridden. It would also then make a little more sense to raise a build-time error if multiple resources define a `storage` with the same name.

**Comment by jgraettinger** [comment]
We caught up on this, and the current plan is to introduce a `StorageMapping` concept which relates a prefix of the global namespace to its applicable storage locations. It might look like:

```
storageMappings:
  acmeCo/sales/: s3://acmeCo-sales-data
  recovery/acmeCo/sales/: s3://acmeCo-sales-recovery-logs
```

During catalog build, we would require that collections and catalog tasks are able to resolve a StorageMapping having the longest matching prefix of the collection/task name. Note that the recovery logs of a catalog task are always under `recovery/the/task/name`.

`recovery` is a reserved prefix which would never be an allowed tenant name.

**Comment by jgraettinger** [comment]
> I don't really see why we'd need to prohibit storage mappings from being a prefix of one another.

Yes, I've debated this also, but arrived at a working conclusion of "if we can't _prove_ that we need to allow storage mappings to prefix other mappings, then better to not allow it". It simplifies the model -- both cognitively and in implementation -- without giving up any representational fidelity. And it can be relaxed later if we discover otherwise.

It's relationship to AuthZ is interesting fallout, but not the rationale.

**Comment by jgraettinger** [comment]
> I would expect that permissions for storage resources are separable from the permissions for other resource types. 

Maybe? This isn't clear to me. If we can get away with a unified / un-typed model, why not go for that ?
