### ISSUE TITLE
capture/materializations: acknowledgements and Apply / Delete RPCs

### ISSUE THREAD

**Issue by willdonnelly** [estuary/flow#272]
Some data sources require explicit confirmation that data has been consumed and will not be needed again. As a concrete example, PostgreSQL expects a `flush_lsn` value from replication clients which will allow it to advance the `restart_lsn` of a replication slot, discard old WAL segments, etc. Similarly some message queues require explicit acknowledgement of delivery and will buffer / resend messages until they're consumed.

But we don't want our connectors to just assume that data has been persisted once they write it to `stdout`, that's just asking for trouble. And I'm told that no heuristic (like "wait 5 minutes after emitting a record") could be used that wouldn't be violated under some possible recovery scenario.

Thus we need to actually implement some sort of explicit commit acknowledgement from Flow to the source connector which tells it "your output has been committed up to <this point> and you will never be restarted from an older state checkpoint".

**Comment by jgraettinger** [comment]
I'm broadening the scope of this to also include:

* Commit acknowledgements for _materialization_ connectors. We've come to recognize that these are needed to, to enable certain workflows where the connector stages data during the transaction, and then idempotently applies it after the transaction  commits (during a new acknowledgement phase). An acute use case is implementing a connector for materialize which must write to a journal with exactly-once sementics. This can be achieved by storing ACK intents in the driver checkpoint, and then writing those ACK intents during the Acknowledge phase.

* Adding an Apply RPC to the capture protocol. For some resources, like logical replication slots, these should be created / allocated during the Apply RPC as we do within Apply of the materialization protocol. Initially this will be a no-op, as it's not directly supported by the Airbyte spec, but we could add it as an extension.

* Adding a Delete RPC to both the capture & materialization protocol. Materialization connectors are responsible for cleaning up resources they've created, such as tables and checkpoints. For captures, this initially would be a no-op (and again, we could potentially extend Airbyte).
