### ISSUE TITLE
Architecture: Determine the best/most secure way to handle secure credentials in the Flow SaaS model

### ISSUE THREAD

**Issue by snowzach** [estuary/flow#278]
We need to be able to provide Secure Configuration Storage of User's configurations.

We believe the most ideal tool to leverage is Hashicorp Vault. It's somewhat the standard in secure credential storage. This is attempting to outline the workflow and process for getting Secure Credentials in and out of Vault as well as how the Secure Configuration will be managed.

### Definitions/Assumptions/Statements
- We will be storing Secure Configurations (SC).
- SC will likely be credentials but could be other sensitive configuration information.
- SC will be stored in Secure Configuration Storage (SCS) outside of the normal management database.
- The management database will store the existence of SC in the SCS along with some metadata but have no visibility into it.
- A Security Group is a logical container that holds Secure Configurations.
- A Security Group construct should exist in both the Management Database and the Secure Configuration Storage.
- A user is granted Read or ReadWrite access to a Security Group. 
- Read access grants a user permission to leverage a SC.
- ReadWrite access grants a user permission to Update/Remove an SC. (User cannot view)
- A Security Group may be the same as a Tenant. If it's not the same, it must only belong to one Tenant.
- Management and visibility of SC in the SCS should be maintained on a per Security Group basis

### Secure Credentials Creation Workflow
- Users are able to provide static SC with sensitive information via the management API.
  - Users assign one of their available ReadWrite Security Groups to the SC during creation.
- Management API stores Information, encrypted at rest, in the SCS
- Management API makes note the SC exists along with any metadata in it's database.

### Secure Credentials View Workflow
- The management API enforces credential visibility for users based on security groups.
- The user is only allowed to see the SC metadata (not the actual SC data)

### Secure Credential Usage Workflow
- When the Flow runtime is ready to leverage Secure Configuration it obtains a ReadOnly token from Secure Configuration Storage that is applicable to the Secure Configurations's Security Group. 
- The Flow Runtime leverages the ReadOnly token to provide the means of fetching the Secure Configuration to the Flow Connector. 
- The method for providing the Secure Credentials to the Connector is TBD

### Day One Features
For initial development we'll start with Static Credentials. 

### Day N Features
Vault supports a myriad of plugins for obtaining temporary credentials that we can add support for in the future. These present some challenges though as it's plausible connectors could run un-interrupted for months and thus some credentials will expire. We need to manage these challenges and ensure that credential expiration and rotations are handled appropriately by the connectors.

**Comment by snowzach** [comment]
Here's the current thought process around how the Secure Connector Proxy would work
![image](https://user-images.githubusercontent.com/7305473/140071897-cb30f0c3-bbe9-4ff9-b141-f61915936e7a.png)

**Comment by jgraettinger** [comment]
Closing because we've achieved the goal of having an architectural consensus. Still more to figure out, but next steps are to start prototyping.
