### ISSUE TITLE
consider warning or disallowing reductions on key fields for catalogs

### ISSUE THREAD

**Issue by jixij** [estuary/flow#291]
The reduction on key fields could change the values of the key during materializations process, which causes [this check against flighted](https://github.com/estuary/flow/blob/12d958d7929a124162cc4aa6745c46a0a5ccd07c/go/runtime/materialize.go#L303-L304) to fail.
(Might be the same for derivations and captures?)

**Comment by psFried** [comment]
I'm tempted to say that the real "fix" here is to disallow all reduction annotations on key fields, but I'm not quite sure if that's right.
In this scenario (materialization) is seems like if we allowed keys to be mutated during reduction, then we'd have no way of knowing whether or not such a document exists in the external system when we go to write it back out. For example, if there were a collection with a `sum` reduction on its `key` field, we could load a document with a key of `1`, then reduce it with another document (also having a key of `1`), and the output would be a document with a key of `2`. There are two possibilites, either they _new_ key already exists within the combiner, or it doesn't. If it _does_, then now when we drain the combiner it's going to have multiple documents with the same key. If it _doesn't_, this would then result in the linked `flighted` check failing.

In the first case, we could _potentially_ back off of the guarantee that keys are not repeated in multiple documents among the store requests in a transaction. In the second case, we'd have to change `exists` from a simple boolean, to something that could also express an explicitly unknown state (`true`, `false`, or :shrug: ). In _either_ case, it's not clear to me whether or not it would break anything or make it more difficult to write a correct materialization driver.

It's also not clear to me that there's a benefit to the user to being able to put reduction annotations on key fields. I'd be curious to hear if anyone can think of a use case that would benefit from that capability.

**Comment by jgraettinger** [comment]
> I'm tempted to say that the real "fix" here is to disallow all reduction annotations on key fields

Agreed with this: we should restrict keyed fields to having a LastWriteWins reduction strategy.

I'd expect that any perceived value of being able to do this can probably be gotten at by having a non-keyed field do the reduction, and to _not_ enforce this constraint will confuse the heck out of people.

**Comment by jgraettinger** [comment]
I'm including this in some current inference / build validation work.
