### ISSUE TITLE
Proposal: `flowctl` Config File Overhaul

### ISSUE THREAD

**Issue by saterus** [estuary/flow#300]
As we discussed recently, `flowctl` already has a config file that it will respect. This is not obvious to new users (nobody but Johnny new this), but it's something we could leverage to eliminate papercuts in the workflow.

1. Automatically generate a config file and make it obvious that it exists and can be edited. Currently `flowctl print-config` can generate a default config, but it doesn't save it. We should change this command to `flowctl config generate` (strawman) and save the contents in a default location (`~/.config/flow.extension`).
2. Add a `flowctl config current/view/edit` (strawman) command to help the user find this config file or open it to edit.
3. Move the `BROKER_ADDRESS`, `CONSUMER_ADDRESS`, and `BUILDS_ROOT` environment variables into the config file (this may already be done). Default them to something sensible so that the user never needs to set these explicitly in a default `temp-data-plane` setup.

## Future Enhancements

As we develop the public managed service, it will be more common for users to default to using the managed service, rather than a local installation. We still want to make it easy for users to launch things locally for testing and switch back to the managed service for production changes. It could be beneficial to provide a concept of "current context" which wraps up the `*_ADDRESS` and `BUILDS_ROOT` settings and allows the user to easily switch which control plane `flowctl` is issuing commands to. This would be familiar to `kubectl` users.

**Comment by jgraettinger** [comment]
This would be great. As an implementation note, all of the configuration file stuff lives in github.com/gazette/core, and most of the heavy lift will be in finding a way to thread this through that's still appropriate for Gazette in isolation.

**Comment by jgraettinger** [comment]
I think this is moot given the new CLI tooling.
