### ISSUE TITLE
`sops` document re-ordering can violate MACs

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#303]
`sops` creates a MAC over the contents and structure of documents it protects.

Meanwhile we parse `sops` YAML or JSON documents using a `serde_json::Value` during catalog build, and re-encode them (always) as JSON. The trouble is that `serde_json::Value` sorts on ascending property name, and it turns out that this changes (violates) the `sops` MAC represented in the document.

My current best idea is to require that config documents having a `sops` stanza are given in already-sorted order, and give a meaningful and actionable error to the user if they're not.

**Comment by mdibaiee** [comment]
`serde` has a crate feature called `preserve_order` which allows it to keep the order of the fields, that is also an option.

See:
- https://docs.serde.rs/serde_json/value/enum.Value.html?search=#variant.Object
- https://github.com/serde-rs/json/pull/80/files
