### ISSUE TITLE
docs: document task log and metrics collections

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#334]
We make no mention currently that we're automatically building these collections on the user's behalf.
We should cover:
1. That they exist, and why
2. What they look like
3. A quick example of materializing them to a database

**Comment by oliviamiannone** [comment]
Just noticed this issue. I believe this documentation I added recently should cover task logs 
https://docs.estuary.dev/concepts/advanced/logs-stats/
https://docs.estuary.dev/reference/working-logs-stats/
And reviewed by Phil - https://github.com/estuary/flow/pull/353
