### ISSUE TITLE
control: prototype data model

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#341]
In design discussions so far, we've identified [a number of queries](https://excalidraw.com/#room=68933c82f663aa3244e4,80thm1TbJDRYG60HM03vmA)
that we need the CPDB to facilitate answers for.

We do have an existing catalog-centric data modeling of entities within build (sqlite) databases that we produce,
and would like to continue to use those build databases as a source-of-truth entities they cover.

However they're insufficient by themselves, as there's a bunch of higher-order state we need to model
such as builds that have occurred, activations of entities @ specific builds,
and the unified set of catalog entities that exist and their relationships _across_ builds.

We have _just enough_ of a handle & consensus on what this needs to cover that it's likely fruitful
to go through an exercise of attempting to mostly ground it out in specific SQL DDL.

**Comment by saterus** [comment]
#### 2021-01-24 Discussion Artifacts:

@jgraettinger Provided a detailed SQL Fiddle that explores the schema, with special focus on data consistency: https://dbfiddle.uk/?rdbms=postgres_14&fiddle=e52bc377c4bf9182047ba2e99c7ecc51

@saterus Provided a Markdown document that explores a breadth of schema concerns. https://gist.github.com/saterus/7efad455b20ef3b433f63c0da2ae61de The prior Excalidraw diagram of relationships is likely helpful to view as well. https://excalidraw.com/#json=K0G47wGUZHQMgL2nFQJij,5PdCJVFpnNGGcaR9W1eLdA

![control-plane-schema-2022-01-24](https://user-images.githubusercontent.com/119613/151216345-cf6a7f36-8259-4382-83f6-d90dd3a3e6a5.png)

---

We're planning on taking the best parts of both of these models. The next steps are to actually continue working on the Control Plane itself and moving the discussions to individual PR feedback as the design evolves with the project.
