### ISSUE TITLE
Docusaurus doesn't like flowctl-rs output (+ one more json>md suggestion)

### ISSUE THREAD

**Issue by oliviamiannone** [estuary/flow#369]
Been getting acquainted with markdown generation commands. They're already quite useful for me as a resource when writing the docs. However, it's not ready to just copy-and-paste because the tagging and unicode crashes docusaurus output (although, as we can see here, github is just fine with it). 

 An example of the `source-postgres` connector spec to illustrate:

ran `flowctl api spec --image=ghcr.io/estuary/source-postgres:dev | jq '.endpointSpecSchema' | flowctl-rs schema-to-markdown > endpoint-docs.md` as directed

Which produced  output formatted like:

| Location | Title | Description | Type | Default |
|---|---|---|---|---|
| *<code></code>* |  |  | object | <code></code> |
| *<code>&#x2F;database</code>* |  | Logical database name to capture from. | string | <code>&quot;postgres&quot;</code> |
| *<code>&#x2F;host</code>* |  | Host name of the database to connect to. | string | <code></code> |
| <code>&#x2F;networkProxy</code> |  | Configurations to enable network proxies. | object | <code></code> |
| <code>&#x2F;networkProxy&#x2F;proxyType</code> |  | The type of the network proxy. Supported types are: ( sshForwarding ) | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding</code> |  | Config for proxy of type sshForwarding | object | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;localPort</code> |  | Local port to start the SSH tunnel. The connector should fetch data from localhost:&lt;local&#x5F;port&gt; after SSH tunnel is enabled. | integer | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;remoteHost</code> |  | Host name to connect from the remote SSH server to the remote destination (e.g. DB) via internal network. | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;remotePort</code> |  | Port of the remote destination. | integer | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;sshEndpoint</code> |  | Endpoint of the remote SSH server that supports tunneling | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;sshPrivateKeyBase64</code> |  | Base64-encoded private Key to connect to the remote SSH server. | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;sshUser</code> |  | User name to connect to the remote SSH server. | string | <code></code> |
| ~~_<code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;&#x2A;</code>_~~ |  |  |  | <code></code> |
| ~~_<code>&#x2F;networkProxy&#x2F;&#x2A;</code>_~~ |  |  |  | <code></code> |
| *<code>&#x2F;password</code>* |  | User password configured within the database. | string | <code></code> |
| *<code>&#x2F;port</code>* |  |  | integer | <code>5432</code> |
| <code>&#x2F;publicationName</code> |  | The name of the PostgreSQL publication to replicate from. | string | <code>&quot;flow&#x5F;publication&quot;</code> |
| <code>&#x2F;slotName</code> |  | The name of the PostgreSQL replication slot to replicate from. | string | <code>&quot;flow&#x5F;slot&quot;</code> |
| *<code>&#x2F;user</code>* |  | Database user to use. | string | <code>&quot;postgres&quot;</code> |
| <code>&#x2F;watermarksTable</code> |  | The name of the table used for watermark writes during backfills. | string | <code>&quot;public.flow&#x5F;watermarks&quot;</code> |
| ~~_<code>&#x2F;&#x2A;</code>_~~ |  |  |  | <code></code> |

To get docsaurus to not freak out, you have to remove all unicode and tagging here. It's pretty time consuming to pick through. 

----

+ one more suggestion: Nested conflg (in this case, network proxy) might be better for docs (IMO) if broken out into a separate table rather than how it is handled here. Not a big deal if that's hard to implement.

**Comment by oliviamiannone** [comment]
Raw version of that table
```
| Location | Title | Description | Type | Default |
|---|---|---|---|---|
| *<code></code>* |  |  | object | <code></code> |
| *<code>&#x2F;database</code>* |  | Logical database name to capture from. | string | <code>&quot;postgres&quot;</code> |
| *<code>&#x2F;host</code>* |  | Host name of the database to connect to. | string | <code></code> |
| <code>&#x2F;networkProxy</code> |  | Configurations to enable network proxies. | object | <code></code> |
| <code>&#x2F;networkProxy&#x2F;proxyType</code> |  | The type of the network proxy. Supported types are: ( sshForwarding ) | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding</code> |  | Config for proxy of type sshForwarding | object | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;localPort</code> |  | Local port to start the SSH tunnel. The connector should fetch data from localhost:&lt;local&#x5F;port&gt; after SSH tunnel is enabled. | integer | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;remoteHost</code> |  | Host name to connect from the remote SSH server to the remote destination (e.g. DB) via internal network. | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;remotePort</code> |  | Port of the remote destination. | integer | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;sshEndpoint</code> |  | Endpoint of the remote SSH server that supports tunneling | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;sshPrivateKeyBase64</code> |  | Base64-encoded private Key to connect to the remote SSH server. | string | <code></code> |
| <code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;sshUser</code> |  | User name to connect to the remote SSH server. | string | <code></code> |
| ~~_<code>&#x2F;networkProxy&#x2F;sshForwarding&#x2F;&#x2A;</code>_~~ |  |  |  | <code></code> |
| ~~_<code>&#x2F;networkProxy&#x2F;&#x2A;</code>_~~ |  |  |  | <code></code> |
| *<code>&#x2F;password</code>* |  | User password configured within the database. | string | <code></code> |
| *<code>&#x2F;port</code>* |  |  | integer | <code>5432</code> |
| <code>&#x2F;publicationName</code> |  | The name of the PostgreSQL publication to replicate from. | string | <code>&quot;flow&#x5F;publication&quot;</code> |
| <code>&#x2F;slotName</code> |  | The name of the PostgreSQL replication slot to replicate from. | string | <code>&quot;flow&#x5F;slot&quot;</code> |
| *<code>&#x2F;user</code>* |  | Database user to use. | string | <code>&quot;postgres&quot;</code> |
| <code>&#x2F;watermarksTable</code> |  | The name of the table used for watermark writes during backfills. | string | <code>&quot;public.flow&#x5F;watermarks&quot;</code> |
| ~~_<code>&#x2F;&#x2A;</code>_~~ |  |  |  | <code></code> |
```

**Comment by psFried** [comment]
Just to clarify, when you say "tagging", are you referring to the use of `<code>`?

**Comment by oliviamiannone** [comment]
Yes. Sorry. Use of <code>. It's ok with these guys: `
