### ISSUE TITLE
Remove sqlite materialization

### ISSUE THREAD

**Issue by mdibaiee** [estuary/flow#442]
Sqlite materialization is the reason the sql library is still in this repository, and we think it's time to get rid of it.

The most challenging part about removing it is that we use it internally for testing a lot.

**Comment by pothibo** [comment]
As I was reading more documentation today, I realized that we have a section in our doc regarding SQLite. If we were to remove SQLite materialization, would it mean we would need to remove this section? https://docs.estuary.dev/concepts/materialization/#sqlite-endpoint

**Comment by mdibaiee** [comment]
PR to migrate materialize-sqlite to an independent connector: https://github.com/estuary/connectors/pull/569

**Comment by mdibaiee** [comment]
https://github.com/estuary/flow/pull/996
https://github.com/estuary/connectors/pull/644
