### ISSUE TITLE
Capture connector containers sometimes left dangling

### ISSUE THREAD

**Issue by psFried** [estuary/flow#467]
I've observed a number of instances where a capture connector is left alive and running after the capture shard has failed. This causes issues with `source-postgres` because the new connector instance is then unable to start when a new term is initialized, because the old container is still using the replication slot. The desired behavior is that we should ensure that connector containers are always killed whenever a shard fails.

**Comment by jgraettinger** [comment]
To clarify a bit, the shard failing shouldn't in-and-of-itself terminate the connector (perhaps it should, but as-implemented it won't). What _should_ happen, though, is that a later un-assignment of the shard _would_ cancel the connector's invocation context, which would get us to the desired behavior.

I do think we should run down why that isn't happening before changing the cancellation semantics around shard failure.

**Comment by psFried** [comment]
Finally started chasing this down, and I've found an issue with signal propagation. This is addressed in #485, which switches over to using the built-in init process for now. `connector-proxy` was not forwarding signals and cleaning up all child processes in all cases. Handling that correctly doesn't seem trivial, since connectors themselves may also spawn child processes. So rather than implement that handling in connector-proxy, I switched to using the `--init` flag for `docker run`, at least for the short term.

**Comment by psFried** [comment]
Also, just to clarify, this signal propagation was broken at the point where the shard is unassigned, and that's where it was fixed. I do think that we should consider shutting down connectors more eagerly when there's a failure, but that's a question that I think we can probably defer to later. At the moment, we leave the connector running indefinitely after a failure, and it continues to read and output data, which just goes into its stdout buffer, which we never read. But they continue to have logs forwarded, which seems to sometimes just add unnecessary noise, but it doesn't seem to be hurting anything apart from that.
