### ISSUE TITLE
Parser Config Strangeness

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#505]
Note that this is relatively early feedback, cause I haven't actually been successful creating a GCS or S3 capture in the UI so far.  They've all failed for various reasons, but this is intended to provide initial feedback on parser config from a UX point of view mostly for @jgraettinger and @psFried .

**Background**
The parser config form is a bit difficult to understand currently for several reasons.  As a user, I'm not really sure what's required of me.

1. There are two separate sections in the UI.  One for CSV and TSV.  Each of which require that I add a delimiter -- this specifically doesn't make sense to me.  I would expect that a CSV would delimit on commas and a TSV would delimit on tabs and therefore, if there were two sections dictating each, we wouldn't actually require that the user input anything?  I also don't really understand the caption which is telling me to use "single-byte characters".  Presumably a tab or comma are single byte characters but that isn't something I could be 100% sure of.
2. A lot of the fields under these seem like advanced options.  As a user, should I be looking at the parser config to be a 100% advanced option section?  Would we automatically just use commas for CSV files and tabs for TSV files and I shouldn't actually have to do anything there for a standard file?
3. After discovery, I didn't actually see a schema output when I put a comma in.  This was a bit surprising for me since I was using a standard csv file and "," as the delimiter.
4. File extension mappings seems like a blank section under headers that nothing can be added to.  Same with "Add Values" under parser.
5. There's probably more but I'm going to hold off here since I feel like I'm not getting this from a UX perspective.  It may be a good idea for us to take a step back and think about design a bit unless I'm missing something...which I probably am.

**Comment by psFried** [comment]
I think this was all addressed by #556 and #591. Closing this for now, but feel free to re-open if there's other issues.
