### ISSUE TITLE
Issues Preventing Deleting Materialization Shards

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#520]
**Problem**
As part of sprint planning, I said I'd clean my shards up, but it's currently not possible to do so with many of them in the UI. Here are some errors that I've seen:

For: estuary/dave-tw/exchange-rates-postgres-rds, estuary/dave/postgres-ga, estuary/dave-tw/exchange-rates-postgres-rd, estuary/dave-tw/postgres-rds-google-analytics, estuary/dave-tw/mailchimp_posgres_rds

`select ll.log_line from public.draft_specs as ds join public.publications as p ON p.draft_id = ds.draft_id join internal.log_lines as ll on ll."token" = p.logs_token where ds.catalog_name = 'estuary/dave-tw/mailchimp_posgres_rds';`

All the same type of error like this:

`[31mFATA[0m[0002] fatal error                                   [31merr[0m="deleting materialization \"estuary/dave-tw/mailchimp_posgres_rds\": exit status 1 with stderr:\n\ntime=\"2022-06-07T18:47:33Z\" level=info msg=\"opening database\" database=dave_saas_stuff host=database-3.ccpi9kwz3vei.us-east-1.rds.amazonaws.com port=5432 user=postgres\nmaterialization estuary/dave-tw/mailchimp_posgres_rds is at version 061b63239ea68800, not the requested 06196a787d220c00\n"`

It would be great if we could delete those.  I think we already fixed the issue that caused the problem.

**Comment by jgraettinger** [comment]
For errors like:
```estuary/dave-tw/mailchimp_posgres_rds is at version 061b63239ea68800, not the requested 06196a787d220c00```

This is because the task was created before the data-plane was hooked up. We should be able to clear them out by first disabling the task (which publishes a new version), and _then_ deleting it.

**Comment by dyaffe** [comment]
Okay, closing this ticket as completed
