### ISSUE TITLE
Improve Error Messaging in Network Proxy

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#555]
**Problem** 
If a user gets information wrong in the network proxy, it leads to no feedback at all and the UI hangs.  One specific example of this is when you get your sshEndpoints port wrong.  If configured incorrectly, it will hang forever.

Try `ssh://dave@35.192.214.194:5432` instead of `ssh://dave@35.192.214.194:22`

**Comment by dyaffe** [comment]
There are a lot of settings in the network proxy and getting one of them wrong is very common.  This makes it so the user doesn't get feedback when that happens and as such I would consider it high priority.

**Comment by willdonnelly** [comment]
Related: https://github.com/estuary/flow/pull/563 which doesn't directly improve the error messaging, but makes it a bit harder to misconfigure SSH forwarding in the first place.

**Comment by willdonnelly** [comment]
Uploaded https://github.com/estuary/flow/pull/564 to refine the error messages a bit more, and once that's merged I think this issue will be fixed.
