### ISSUE TITLE
Network Tunnel config for selected connectors only

### ISSUE THREAD

**Issue by mdibaiee** [estuary/flow#584]
- [ ] https://github.com/estuary/flow/pull/583
- [ ] Switch existing connectors to use `address` property
  - [ ] materialize-postgres
  - [x] ...?

**Comment by willdonnelly** [comment]
I believe this issue isn't actually complete until https://github.com/estuary/flow/pull/583 is merged, right?

**Comment by mdibaiee** [comment]
Yes, this was an automated closing of the issue. Thanks Will.

**Comment by mdibaiee** [comment]
This has been deployed to production and I checked it, it looks like it's working as expected!
