### ISSUE TITLE
Parsing & Schema Inference Performance Optimization

### ISSUE THREAD

**Issue by williamhbaker** [estuary/flow#681]
As part of the current capture "discovery" process, parsing data and performing inference can take a considerable amount of time.  This could be considered a narrowly-focused subset of the "slowness" problem described in the  [discussion here](https://github.com/estuary/flow/discussions/640). This issue is purely describing computational time for parsing a fixed subset of data, and then performing schema inference on it.

### Background

As part of investigating the root cause for the problem fixed by https://github.com/estuary/connectors/pull/344, it was found that parsing and performing schema inference on a large static file took quite a long time.

The file in question is a CSV file containing [2018 Yellow Taxi Trip Data](https://data.cityofnewyork.us/Transportation/2018-Yellow-Taxi-Trip-Data/t29m-gskq). It is a 9.7 GB of CSV data containing about 112 million records.

A bug in the `source-s3` connector caused the discovery process to try to parse & infer schema over this entire file without respect to [timeouts](https://github.com/estuary/connectors/commit/5202214d4310447dc2d37ce039d8f610d75fc9f3). On our production nodes, the discovery process could not complete within an hour. Although the underlying bug in the connector has been fixed, one might expect that a file of this size could have been completely "discovered" within an hour.

### Current Performance

I produced some initial benchmarks working locally with this dataset. High-level observations were that parsing the CSV to JSON did indeed take quite a long time, but processing the resulting JSON through the schema inference tool took several times longer. All data below is based on running the `flow-parser` & `flow-schema-inference` binaries on a 2021 M1 Macbook Pro.

For 1,000,000 records of 2018 Yellow Taxi Trip Data:
- Parsing CSV (~88 MB)-> JSON: 2.41 secs
- Parsing the resulting 1,000,000 JSON records (~380 MB) -> JSON: 5.13 secs
- Schema inference on 1,000,000 JSON records: 9.44 secs

Parsing JSON to JSON was done as a sanity check of CSV parsing. It does not seem that there is anything abnormally slow about parsing from CSV to JSON when compared to parsing from other formats. The most significant benefit could be realized from optimizing schema inference.

Flamegraph of schema inference: ![inference](https://user-images.githubusercontent.com/55118525/191259731-c7817a40-a265-4950-937c-41acf5487b2c.svg)

**Comment by jgraettinger** [comment]
I think we can close this, since we no longer do inference during discovery ?

**Comment by williamhbaker** [comment]
Yeah, there's probably some performance improvements that could be made for parsing & inference but it's not a part of the publication process anymore so definitely not a huge priority.
