### ISSUE TITLE
Collect prometheus metrics on connector resource utilization

### ISSUE THREAD

**Issue by psFried** [estuary/flow#708]
We'd like to surface more metrics on connector containers that are run by Flow. The goal is to associate the metrics with each shard.

Some things that seem worth collecting:

- Memory usage
- CPU
- Network
- disk?

An example prometheus metric would be something like `flow_connector_mem_rss[shard="capture/acmeCo/foo/bar/00000000-ffffffff", image="ghcr.io/estuary/source-hello-world"]`. The shard name being attached to the metric will help us to aggregate the total resource utilization of each Flow task.

**Comment by jshearer** [comment]
We would also like to make sure to tag this data with:
* Connector type (`capture-firstore`, `materialize-postgres`, etc)
* Tenant

**Comment by dhammika** [comment]
We can add a container name and scrape stats of all containers on the host.  
https://github.com/estuary/flow/blob/5dbd8f13820df623bc0cb6360520909d82a7cd46/go/connector/run.go#L125-L146
but names only allow `[a-zA-Z0-9][a-zA-Z0-9_.-]`

**Comment by psFried** [comment]
This seems like a good idea that's worth investigating further. I'm not very knowledgeable about the prometheus metrics exposed by Docker, but it seems very likely that they'd have what we need. One question I'd have is how we could correlate the containers in the Docker metrics with the Flow shards. The container name doesn't allow `/`, which is in all shard names, so I don't think it could be as simple as setting the container name to the name of the shard. I'm sure there are other options, though they may require doing some transformation of the labels in prometheus rules (not the end of the world).

**Comment by dhammika** [comment]
> 
> The container name doesn't allow `/`, which is in all shard names, so I don't think it could be as simple as setting the container name to the name of the shard. 

Ya, container names are more restrictive. ShardIDs can have non-alphanum chars including '/',
https://github.com/gazette/core/blob/54b34a7d85ec6061ddc97d032b7223a0c03aa330/broker/protocol/validator.go#L87
https://github.com/gazette/core/blob/54b34a7d85ec6061ddc97d032b7223a0c03aa330/consumer/protocol/shard_spec_extensions.go#L34
It's not ideal but I think it'll still get us more visibility into connector resources.

**Comment by dhammika** [comment]
Based on offline chat, we can collect connector stats from grafana agent's docker metrics tagged with readable ShardID/ImageID tags. 
However, adding ShardIDs looks somewhat non-trivial. Driver API can take a ShardID string but I'm not sure if that API is always call in a shard context.    
https://github.com/estuary/flow/blob/d0f61cdd6369d1cd2bbd931641506b6bad3b1002/go/capture/endpoint_types.go#L16-L20
https://github.com/estuary/flow/blob/d0f61cdd6369d1cd2bbd931641506b6bad3b1002/go/materialize/endpoint_types.go#L16-L20
ie. "spec", "discover" API calls,  
https://github.com/estuary/flow/blob/d0f61cdd6369d1cd2bbd931641506b6bad3b1002/go/flowctl-go/cmd-api-spec.go#L84-L86
https://github.com/estuary/flow/blob/d0f61cdd6369d1cd2bbd931641506b6bad3b1002/go/flowctl-go/cmd-api-discover.go#L47-L49
also in bindings, believe these are rust/cgo entry points. 
https://github.com/estuary/flow/blob/d0f61cdd6369d1cd2bbd931641506b6bad3b1002/go/bindings/build.go#L141-L142
https://github.com/estuary/flow/blob/d0f61cdd6369d1cd2bbd931641506b6bad3b1002/go/bindings/build.go#L174-L175

**Comment by psFried** [comment]
Yeah, it's true that we don't always have a shardID when running connectors. For example, `build.go`, `cmd-api-discover.go`, and `cmd-api-spec.go`, are only used during the build/publish process, not at runtime. We'll only have a shardID for the runtime invocations, so I think the shardID parameter would need to be optional.

**Comment by dhammika** [comment]
Still have to figure out cadvisor/collector side of the puzzle. I don't think it's a major effort but we still have to get cadvisor and config snippets into `dind` image.  Even though we plan to move away from docker in orchestrating connectors we'd still need these metrics. Even for short-term, it's infeasible to operate without meaningful metrics.

**Comment by dhammika** [comment]
Agent deployed in prod,  
![connector-metrics](https://user-images.githubusercontent.com/262792/201189234-2ac6614f-a425-48ef-a32e-9310bc786d70.png)
