### ISSUE TITLE
logging: middleware tweaks

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#713]
Summarizing a recent conversation:

We have a number of loosely coupled components which produce logs that we ultimately want to thread through and consolidate. Our current approach is to
  1) attempt to push down the log-level predicate to subordinate processes (like connectors)
  2) to attempt to extract structure from logs of subordinate processes, and
  3) to apply level-based filtering as middleware over those logs.

We additionally attach an INFO level to logs for which we can't extract any structure.

This is less-than-great in a few areas. The control-plane agent defaults to a WARN log level so-as not to span the user. However, if a connector panics with a stack-trace, or outputs an unstructured error before exiting with non-zero status (the default for [go-flags](https://github.com/jessevdk/go-flags)), then we end up filtering out these lines as middleware.

We want to adjust our position in the following ways:

 1) We will _not_ implement any log filtering as middleware. We will be consistent in pushing down a level predicate in all cases, but anything that a subordinate process logs is going to be surfaced.
 2) We *will* continue to extract structure from logs where possible, and propagate that into the `ops/$tenant/logs` collection, but we will stop using a local logger which applies filtering (e.x. `logrus`) during invocations of the control-plane agent, and instead directly forward to stderr of the parent process.
 3) Instead of mapping unstructured log lines to `INFO`, we'll introduce a level `RAW` which exists outside of the traditional `DEBUG/INFO/WARN/ERROR` ordering.
 4) We'll update [`connector/run.go`](https://github.com/estuary/flow/blob/master/go/connector/run.go#L354-L362) to collect the prefix _and suffix_ of stderr output from an invoked connector, modeled on how the Go standard library does it (as its internal implementation detail). These will continue to be captured as terminal errors coming out of a failing connector invocation.
 5) We will *stop* forwarding logs to the stderr of the `flow-reactor` altogether. We'll log a terminal error as produced by 4), but other output will be available only in the `ops/$tenant/logs` collection.

**Comment by psFried** [comment]
This looks good to me. Thanks for writing it up. There's one detail that I think we might want to discuss further:

> stop using a local logger which applys filtering (e.x. logrus) and instead directly forward to stderr of the parent

I think I might argue for excluding the `flow-reactor` from this, and allowing it to still filter based on its log level. (Still directly forward output in `flowctl-go`, though) Do we want all logs from the `ops/$tenant/logs` collections to be duplicated in the stderr of the reactor? Or put another way, do we want to allow users to control how much data is logged by the `flow-reactor` process by changing the log level of their shards? OTOH, the log volume might just be a non-issue, so :man_shrugging:

**Comment by jgraettinger** [comment]
Thanks, I edited above ☝️ in response to this, to note that we should altogether stop having task logs going into the `flow-reactor` stderr. Forwarding to stderr would only be for discover / validate / apply RPCs done by the control-plane agent.

**Comment by dhammika** [comment]
I see ops logs are filtered and duplicated in into stderr, is # 1 about removing these stderr forwarding?
https://github.com/estuary/flow/blob/0522b01b6001702149ce7c8e0b0fe474841a8cee/go/runtime/ops.go#L193-L195
https://github.com/estuary/flow/blob/0522b01b6001702149ce7c8e0b0fe474841a8cee/go/runtime/ops.go#L212-L214

Also connector stderr is logged as INFO logs.  Is # 4 to propagation these logs to stderr of the invoking process (flow-go) instead? 
https://github.com/estuary/flow/blob/0522b01b6001702149ce7c8e0b0fe474841a8cee/go/connector/run.go#L203

**Comment by jgraettinger** [comment]
> I see ops logs are filtered and duplicated in into stderr, is # 1 about removing these stderr forwarding?

We want to remove them from the stderr of the flow reactor running in production.
But, we do want to pass them through when running `flowctl-go api build` and `flowctl-go api activate`, such as is done by the control-plane agent.

> Also connector stderr is logged as INFO logs. Is # 4 to propagation these logs to stderr of the invoking process (flow-go) instead?

As per 3, we want to map connector stderr log lines which are unstructured into a `RAW` level.

Re: 4, we currently have behavior where, when a connector fails (exits with non-zero status), we gather the leading lines of its stderr output and bundle that into a Go error which gets bubbled up to reflect a shard failure. These errors are in turn serialized into Etcd and from they're displayed in the UI. Right now we gather only a suffix, which means that a noisey connector will have more stderr output than fits in the buffer we'll use, and lines having the actual fault get dropped. What's we'd like to do instead is do what the Go standard library does, and collect both a bounded prefix and a suffix of logs to wrap in errors of this kind.

**Comment by dhammika** [comment]
Log plumbing in `connector_init` will address # 2 and # 3 and output structured logs in json.  
For # 1 and # 5, I've patched following forwarder issues in #810 
- Remove level based filtering
- Propagate raw text output as `WARN` instead of `INFO` 
- Stop tee`ing connector stderr into reactor's 

It's still possible to get stack dumps in runner's stderr and they'll get forwarded into ops collection as `WARN` logs.

**Comment by jgraettinger** [comment]
closed via #812
