### ISSUE TITLE
`doc::JSONPointer` treats integer-like properties as `Token::Index` instead of `Token::Property`

### ISSUE THREAD

**Issue by mdibaiee** [estuary/flow#714]
After #676, `doc::JSONPointer` treats integer-like properties as `Token::Index` instead of `Token::Property`, this leads to ambiguity when using this interface. See the discussion here: https://github.com/estuary/airbyte/pull/46#discussion_r992250679

**Comment by jgraettinger** [comment]
This is intractable ambiguity of the JSON pointer spec.

If you have a pointer `/foo/1/bar`, then `{"foo": [null, {"bar": true}]}` and `{"foo": {"1": {"bar": true}}` are both documents to which that pointer applies.

When querying a pointer from a document, it handles this case and looks for a property named as the string conversion of a `Token::Index`.

Can you expand on the behavior you'd be looking for?

**Comment by mdibaiee** [comment]
@jgraettinger ah I see, then it's a matter of handling this case in airbyte-to-flow. I guess it's possible by looking at whether the type of the parent of the integer is an array of an object, and treat it accordingly.

I was initially wondering if such a behaviour of using information about the parent of the document could help in distinguishing between the two cases, but `doc::Pointer` is not concerned with JSONSchema at all so I don't think it can make such distinction.
