### ISSUE TITLE
Test Filtering

### ISSUE THREAD

**Issue by psFried** [estuary/flow#75]
It would be nice to have a way of running a more limited set of tests to make it easier to sort through the output when debugging a specific test case.

I'm proposing to add a `--filter` flag to the `flowctl test` subcommand, which would accept a string argument that we use to filter test cases by name. I'm not sure what the best behavior would be for matching test cases, so open to suggestions. It's tempting to just always treat the argument as a regex, since it might provide more flexibility, and the common case where the value doesn't include special regex characters (e.g. `.*`) would pretty much just do what you expect. But that could get more complicated than it's worth, so maybe something like just exact match or a prefix match would be easier to work with. Ideas welcome.

An additional motivation for this is the feature discussed earlier to enable more verbose test output (e.g. showing the results of each reduction operation). The verbosity of the output would make it impractical to use such a feature without some ability to focus on a single test case at a time.

**Comment by jgraettinger** [comment]
Will re-open when this is better motivated.  A nice pattern today is to name the specific flow.yaml with the tests you want.
