### ISSUE TITLE
Allow Derivation Cycles

### ISSUE THREAD

**Issue by psFried** [estuary/flow#81]
We should relax our current restriction on cyclic dependencies in order to support more operational decision-making use cases. The thought is that the runtime machinery (shuffle service, etc) _should_ already support this, and the primary need is just to relax the build-time restrictions.

[ ] Allow cycles in derivation dependencies (allow both A -> B -> A and A -> A) during catalog builds
[ ] Change representation of collections in flow.yaml to be an object instead of an array. The keys will be the collection name.
[ ] Add a timeout to `flowctl test` so we can bail if the user creates an infinite loop

**Comment by jgraettinger** [comment]
Done!
