### ISSUE TITLE
Issue with publications that contain more than 1 test

### ISSUE THREAD

**Issue by williamhbaker** [estuary/flow#813]
Several times I have noticed when I try to publish a catalog that has more than 1 test, the publication fails with:

```
2022-11-21T14:49:45Z temp-data-plane:2> ERRO[0008] protocol error (invalid state or invocation)  error="\"InvalidState\"" logSource=derive
2022-11-21T14:49:45Z test:2> FATA[0005] fatal error                                   err="reseting internal state between test cases: rpc error: code = Unknown desc = clearing registers of shard derivation/ops/ops/catalog-stats/00000000-00000000: protocol error (invalid state or invocation)"
2022-11-21T14:49:46.354789Z ERROR flowctl::draft: scope= detail=one or more test cases failed
Error: failed with status: testFailed
```

Need to find out exactly what circumstances are required to reproduce this, but it seems like a real issue.

If I split the publication up so that each publication only has a single test to run, I am able to get the catalogs running.

**Comment by williamhbaker** [comment]
I have tried coming up with a simple reproducer of this without luck so far.

A sure way to get this error is to do the following with a local stack:
- Provision a new tenant using directives, for example `bobCo/`.
- Give your user an admin grant for both `ops/` and `bobCo/`.
- Create a draft, and add `ops/ops/catalog-stats-view` & `ops/bobCo/catalog-stats-view` to it with `catalog draft --name ...`
- Try to publish this draft and observe the error

I have tried with simple flows, combining different splits of publications, the user that created the thing, etc. and haven't been able to reproduce it. It might have something to do with the complexity of the tests and/or derivation documents, as I have only been using basic "hello world" types of documents. The `catalog-stats` flows have more extensive tests and document structures which might be triggering something.

**Comment by jgraettinger** [comment]
This was due to the special nature of the `ops/$tenant/stats` and `ops/$tenant/logs` collections. Specifically, what happens is that a test over a derivation that reads from either of these collections, where the derivation itself lives under $tenant, causes new writes to those collections to occur -- which then confuse the test runner, which is expecting to strictly control when new data is ingested to the collections under test.
