### ISSUE TITLE
dpg: accept HTTP POST -> ingest capture

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#814]
As a user, I want to be able to POST documents directly into a collection through an ingest capture.

For example, I minimally should be able to POST a single document in a way that broadly works with how web hooks are typically implemented:

```bash
$ curl --data-binary '{"hello":"world"}` https://the-data-plane-gateway-host.estuary.dev/name/of/capture/the-binding-name
```

It would be _nice_ to be able to POST vectors of documents to multiple bindings of the capture as a single transaction:

```bash

$ cat inputs.json
{
  "the-binding-name": [{"doc": 1}, {"doc": 2}],
  "other-binding-name": [{"more":"docs"}]
}

$ curl --data-binary @inputs.json  https://the-data-plane-gateway-host.estuary.dev/name/of/capture
```

In the future we'd like to support a streaming API as well, likely web sockets with full support for exactly once semantics, but this isn't a priority right now.

Breaking this down a bit more, users are able to capture into "ingest" captures, which already exist within the Flow specification. As with any other kind of capture, ingest captures bind to multiple collections and each such binding has a user-defined name (`the-binding-name` above). Only collections explicitly bound by the ingest capture can be ingested into, but the user is able to update the capture to change the bound collection without changing the resource name (this avoids breaking existing web hook URLs that may be in use).

Ingest captures support a bidirectionally streamed gRPC API with driver checkpoints and other bits needed for true exactly-once semantics, and the Flow reactor offers up this API today:

* [Push Runtime server](https://github.com/estuary/flow/blob/master/go/protocols/capture/capture.proto#L79-L130)

It's implemented in the runtime here:

* [Implementation of this interface in the runtime](https://github.com/estuary/flow/blob/master/go/runtime/push.go)

We have a few bits of work left to fully realize ingest captures from end-to-end:

 * There's a small bug of omission in the runtime where we're not currently sending the `Opened` message in response to the client's `Open`. We should fix that first.
 * Then, we need to implement HTTP handlers in the data-plane gateway which offer POST of single documents and (as a fast-follow) multiple documents.

**Comment by psFried** [comment]
This issue was resolved, though in a different way than described here. We went with an approach that allows arbitrary network access to connector containers. This is described in #868. The actual implementation of HTTP POST captures was merged in estuary/connectors#565
