### ISSUE TITLE
Captures Protocol

### ISSUE THREAD

**Issue by psFried** [estuary/flow#83]
I'd like to kick off another conversation on Captures. The ultimate goal of this conversation is to
work towards a design for handling the `captures` described in #68. In #72 the takeaway was that we
think we can handle the issues brought up there by introducing source "priorities" in derivations.
Therefore, we don't need to model the concept of batch vs streaming data in captures, and we can
treat all captures as continuously updating.

Similar to Materializations, it would be nice to standardize a Protocol for Captures. Each capture
conceptually represents some "Driver" process managed by flow that reads data from some source
endpoint and appends it to a collection. So the main question is really just "How's that work?".

This brings up a number of other questions, which I'll try to outline below as
a way of kicking things off. Please add any that I may have missed.

**Formats and Parsing**

I see two fundamental approaches we could take with formats and parsing:

1. The Driver is fully responsible for converting all data into JSON that validates against the
   collection schema.
2. The protocol allows the driver to return data in one of several possible formats, and flow will
   handle parsing and conversion into JSON.

In either case, I think the user will need to supply the desired format in the `captures` of their
flow.yaml. I think we should avoid any sort of content-type detection, and force the user specify
exactly what format to expect for each capture.

The downside with the first option is that we could end up with a crappy user experience if
different drivers have different parsing behaviors. For example, when you parse a CSV file from S3
and it works fine, but capturing the same exact CSV file from a different driver doesn't work. This
is surely not a problem we'd have if we implement all the drivers ourselves, since we'd just be
careful to always delegate to the same implementations, but it would certainly be an issue for any
Drivers that were developed out of band.

The second option seems much better, but it requires that we also define a "parser" protocol if we
want to allow capturing things in formats that we don't support out of the box.

My instinct at this point is that we should start off by going with the second option, where we
expect the Driver to return data in the specific format given by the user. But I think we should
start by only supporting the few formats we support today, and defer any design or implementation of
a "parsers" protocol. The goal being simply to manage the scope in the short term.

Compression potentially adds another layer of complexity here, as you'd ideally want to be able
treat decompression as an optional separate step before parsing. For example, we likely wouldn't
want separate formats for CSV compressed with gzip vs lz4. We'd instead prefer to have the
decompression be a separate thing that could be used on files in any format.

**Scaling and Partitions**

The other question is how we should handle captures of high volume data. This one is tricky
because we could easily come up with multiple different definitions of "high volume", and they may
not all warrant the same approach. Source data could be arriving at a relative trickle, but have an
enormous history to catch up on. For example, an S3 bucket that has a CSV file added to it daily
might have years of history to catch up on when the capture first starts. This is different from a
Kinesis stream, for example, which could have a continuous high volume, but likely more limited
history. The partitions of the Flow collection add another possible dimension to this. Would we
scale out ingestion the same way for a partitioned collection as we would for a non-partitioned one?
As if we needed another dimension to add, the source data may also be partitioned or not. Some
sources (e.g. S3) may be ambiguous about this or support either partitioned data or not.

I don't have a strong instince of how we should handle this one right now.

**Fault Tolerance**

Captures may fail and need to be restarted, and we need a contract that can allow for resuming
failed captures while avoiding missing or duplicating data to the greatest extent possible.
Obviously some systems will be easier to work with than others in this regard, and in all cases
there will be caveats to whatever guarantees we make. So the challenge here is to design the
protocol to allow for the maximal fault tolerance guarantees that can be supported by each system.
No matter what, there will be possible scenarios where we could "miss" data. For example, an
S3 capture fails in the middle of reading a file, but the file is modified before the capture is
started up again. Or a Kinesis capture fails for a stream with a short retention period and it takes
longer than that to restart the capture.

**Monitoring and Error Reporting**

This may or may not be something that needs accounted for in the protocol per se, but it's a concern
we have to address somehow. A worst case scenario would be something like a deadlock within the
Driver that results in no records or errors being returned. This could be difficult to distinguish
from a legitimate "quiet period" where no records are being returned. Of course we can make no guarantees
about reporting all driver errors, but we should consider that we'd like monitoring of capture
Drivers to be as consistent as possible, so it might be a good idea to include some sort of "heart
beat" in the protocol. Then again, there may be other ways of handling this that don't involve the
protocol.

**Comment by jgraettinger** [comment]
Closing as implemented.
