### ISSUE TITLE
Make it easier to work with specs locally with flowctl

### ISSUE THREAD

**Issue by psFried** [estuary/flow#832]
There's a number of UX improvements that seem important for `flowctl`. The goal is to introduce some new subcommands that are more high level for handling common scenarios. These would augment, not replace, our existing subcommands. The names here are placeholders, so feel free to suggest alternate names.

`flowctl catalog pull-specs`:

It should be easier to pull specs from the control plane into a local directory. This subcommand does just that. It pulls directly from `live_specs`, and does not require a draft. Unlike `draft develop`, this command will merge the selected catalog specs with the ones that are in the directory. This behavior is optional, but enabled by default. The goal is to prevent overwriting any new specs that someone added to their local files. Note that the merge behavior is only to merge the set of catalog specs. Individual specs, schemas, etc. are just overwritten if they exist, though there should be flags for bailing out early in that case.

`flowctl publish|test|`:

It should also be easier to take a bunch of specs from your local directory and publish them. Currently, this requires the extra step of creating a draft. There's a number of other tweaks we can make to help with this.

First, we should relax our validations around `import`s. We'll still resolve imports, but no longer require that a given spec's resource `import`s that of another spec. This relaxation makes it easier to work with a subset of specs in your local directory. For example, if you want to publish only the specs in `acmeCo/foo/*`, then you can just do that without first needing to adjust the imports.

Second, you should be able to `publish` a set of specs by naming a directory. This takes advantage of the hierarchical layout to allow things like `flowctl publish --all acmeCo/sales/` to publish all the specs recursively found under the given directory. You'll still be able to pass `--source` to use a single file, but allowing selection of specs based on a recursive directory search is intended to save users from needing to add `import`s in order to publish specs that they've added.

**common selection criteria**

We should establish some common arguments for selecting 0 or more specs from the catalog. These arguments would provide some much needed help for the `catalog list` subcommand, which currently can only list _everything_ you have access to. But we should also use the same common arguments for any other subcommands that select 0 or more specs, such as `catalog pull-specs`. The specific arguments are:

- `--prefix <prefix>` selects all items whose name starts with the given prefix.
- `--<type>` (e.g. `--captures`, `--collections`, etc.) would filter the selection to only include items of the given type
- `--name` select an individual item by name
- `--expand-dependents` expands the selection based on the dependency graph of `reads_from` and `writes_to`. For example, `catalog list --name acmeCo/myCapture --expand-graph` would return all items that transitively depend on that capture. This makes it easy to identify the specs that will need re-created if you need to re-create the capture, and can also help make sense of complex graphs.

**Comment by jgraettinger** [comment]
> Regarding the --prefix / --name / etc arguments for catalog list, would it be feasible to support something along the lines of --pattern <regexp>?

A subtext is that we'd like to adopt labels and label selectors as a generalized selection and grouping mechanism for tenant flow specifications. The selectors that @psFried has proposed (prefix, type, and name) are deliberately very in keeping with how "meta" labels work in gazette: journals have meta-labels `prefix` and `name` which are automatically added to their literal labels, and can be used in selectors. It's clear how these flags could be transparently shifted to a labels & selectors infrastructure.

`regexp`, though, can't be, and for that reason I think we should be cautious. Instead, we want users to be able to define their own ontologies via additional supplied labels, and then have a way to select over them.

**Comment by psFried** [comment]
@willdonnelly Do you happen to have a particular use case in mind for that? I'd be curious to hear more about it, if so. Technically, we _could_ support that fairly easily, but I'm also hesitant to do so in the absence of a compelling need, for the reasons @jgraettinger mentioned.

**Comment by willdonnelly** [comment]
> Do you happen to have a particular use case in mind for that?

It's like 80% selfishness really; if I want to do something with a particular task I usually just do something like `flowctl catalog list | grep wgd | grep mysql` or whatever and then copy-paste the full name of the thing I intended.

I do think there's some general utility as well, for instance I could easily imagine wanting to work with `acmeCo/.*/source-mysql` or `.*wgd/test-mysql-20221206.*` and other sorts of patterns where it's fairly easy to type a regex (or a glob pattern) but kind of a pain to copy-paste a bunch of distinct names or otherwise figure out some way of referring to just the entity of interest.

Like, don't take this as a super strong opinion, I'm just throwing out an idea that you're entirely free to disregard. But I'm doubtful most organizations will actually be principled enough that they can use custom labels, and I expect that with the proposed set of filters I will personally end up ignoring them and just going `flowctl catalog list | grep whatever; flowctl do-thing --name <copy-pasted-name>`. And from that perspective it kind of makes sense to cut out the busywork and do `flowctl do-thing --pattern whatever`.

**Comment by psFried** [comment]
In _that_ case, I think my own inclination would be to incorporate something like `fzf` or [skim](https://github.com/lotabout/skim) to allow selecting something. It's nice because it makes the search process much more dynamic, and can even show previews. It's kind of a pain to use with `flowctl` at the moment just because the table format isn't conducive to that type of thing. But I'm sure we could put together a script using that and `jq`, and even using it as a library is pretty easy. What would you think of an interactive UX like that?
