### ISSUE TITLE
Use a cloud KMS in `estuary-sandbox` for local development

### ISSUE THREAD

**Issue by psFried** [estuary/flow#844]
When running Flow locally, we need to use a KMS that's in the `estuary-sandbox` GCP project. The config-encryption service should be configured to use the new KMS. This probably also means re-encrypting some sops documents that are currently encrypted using the helpful-kingdom KMS.

**Comment by jgraettinger** [comment]
This is done?

**Comment by psFried** [comment]
Closing, as this is done.
