### ISSUE TITLE
listen to docker image changes on ghcr and trigger connector_tag updates

### ISSUE THREAD

**Issue by mdibaiee** [estuary/flow#850]
At the moment it's a manual process to ask the agent to update a connector's spec, etc. by updating `job_status:{"type":"queued"}`. 

GitHub API supports [setting up webhooks](https://docs.github.com/en/rest/webhooks?apiVersion=2022-11-28), so we can use that to automatically listen on changes to image updates.

Alternatively we can just poll for updates to a connector image, and trigger a job if we detect it has changed. This approach works for local instances as well.

We want a way for this to work on local instance and GitHub Codespaces too since this is a major friction point when iteratively testing a connector.

**Comment by jgraettinger** [comment]
Let's be careful not to conflate local vs production uses. For local dev, the install connector script could do this, or a blanket update of connector tags, etc. this can be very light weight

For production, this would apply after code review and merge, correct? Would pg_cron or some similar polled refresh of a tag suit? The downside of webhooks is that it's very specific to ghcr.

**Comment by mdibaiee** [comment]
> Let's be careful not to conflate local vs production uses. For local dev, the install connector script could do this, or a blanket update of connector tags, etc. this can be very light weight
>
> For production, this would apply after code review and merge, correct? Would pg_cron or some similar polled refresh of a tag suit? The downside of webhooks is that it's very specific to ghcr.

For local / codespace development environment, the install connector script can't always reach the control-plane, e.g. when connector is being built in a Codespace but the dashboard is running on a local box, and my current pull-request doesn't address this either.

A polling refresh would work for both use cases, but it won't be _fast_, and that's what's missing for dev environment. I can trigger an update using a `curl` or manually through the supabase studio, but it's extra time and effort, and if it takes a few minutes to refresh automatically, I will probably still end up refreshing it manually myself.

For production, polling may work, I don't have something against it, other than it's also slow. The current approach I'm taking is actually not a real webhook from GitHub, but a github action that sends a HTTP request to a Supabase function, asking it to refresh a connector. This action is run after we build and push the new image of a connector in our CI.

**Comment by mdibaiee** [comment]
https://github.com/estuary/connectors/pull/464 and https://github.com/estuary/flow/pull/849 need review

**Comment by mdibaiee** [comment]
solved in https://github.com/estuary/connectors/pull/486 and https://github.com/estuary/airbyte/pull/101
