### ISSUE TITLE
`flowctl typescript generate` does not work well with read-only collections

### ISSUE THREAD

**Issue by psFried** [estuary/flow#862]
Say you want to create a derived collection (`aliceCo/foo`), using a source collection that you only have read access to (`bobCo/bar`). What you'd do today is:

- run `flowctl catalog pull-specs --name bobCo/bar` to pull down the spec of the source collection
- define the spec for `aliceCo/foo` in `flow.yaml` or `aliceCo/flow.yaml`
- Run `flowctl typescript generate`, and implement your lambda(s)
- Run `flowctl test|publish`

The problem is that it's easy for users to end up in a scenario where `flowctl test|publish` will include the `bobCo/bar` spec, which results in an authorization error if you only have read access to it. A user would end up in that situation if they defined the spec for `aliceCo/foo` in `flow.yaml`, which will have an `import` of `bobCo/flow.yaml`. Or they might also have an `import` of `aliceCo/flow.yaml` and define their derivation spec there, which would also result in the authorization error.

I can see at least two perspectives on how we might tackle this, and I don't think they're mutually exclusive.

One perspective would be to say that we should just stop adding `import`s automatically, and thus also stop generating the top-level `flow.yaml` when you run `pull-specs`. The imports are never required, and the ergonomics of `--source flow.yaml` (which the imports afford us) don't seem significantly better than `--source-dir .`. And `--souce-dir` can generally solve the same problem of giving the user a way to apply multiple specs with a single command, so the top-level `flow.yaml` may not be missed.

Another perspective would be to ask why the user should have to run `pull-specs` in the first place. If all they want is to generate typescript classes for use in their derivation code, then we ought to teach `flowctl` to just fetch the source collection specs automatically. This way there's never a need to run `pull-specs` for things that you don't have `admin` access to (we could even emit a warning if you do) and thus you avoid the situation that gave rise to the authorization error.

Having `flowctl typescript generate` automatically fetch whatever specs it needs seems like an obvious win to me, but LMK what you think @dyaffe . I'd also be curious to hear from others on whether the top-level `flow.yaml` still makes sense now that imports are no longer required, or if you think we should implement that instead of, or in addition to, automatic fetching. Of course other ideas are welcome, too.

**Comment by dyaffe** [comment]
Are there any potential downsides with having `flowctl typescript generate` automatically fetch whatever specs it needs?  

This also sounds like an obvious win to me and I don't see anything but upside, but want to make sure that I'm not missing anything.

**Comment by psFried** [comment]
No downsides that I can think of, really
