### ISSUE TITLE
`flowctl draft author` should prune specs that aren't in the local sources

### ISSUE THREAD

**Issue by psFried** [estuary/flow#865]
Say you run the following steps:

- `flowctl catalog draft --name acmeCo/foo`
- `flowctl draft develop`
- Rename `acmeCo/foo` => `acmeCo/bar` in the local spec files
- `flowctl draft author`
- `flowctl draft publish` :boom: your draft includes both `acmeCo/foo` and `acmeCo/bar`

There's not an obvious (to me) _best_ way to handle this, but any of these options seem significantly better to me:

- `draft author` clears all specs from the draft before adding new ones. This way your existing `acmeCo/foo` remains untouched.
- `draft author` changes all specs in the draft to `null` (triggering the deletion of the live specs upon publication) before adding new ones. This way your existing `acmeCo/foo` will be deleted by the publication.
- `draft author` accepts an argument similar to `--existing abort|keep|overwrite|merge-spec` from `catalog pull-specs`, which explicitly says what to do with an existing draft specs.

Given that there's now, with the introduction of `catalog pull-specs|test|publish`, relatively few reasons to use `draft` at all, my inclination is to have `draft author` simply clear all specs from the draft before adding new ones. It's a super easy change to make, and addresses the biggest foot gun. It would also be easy to add a flag to allow opting in to the current behavior.

**Comment by jgraettinger** [comment]
> my inclination is to have draft author simply clear all specs from the draft before adding new ones

I think we can just do this, without flagging for the prior behavior.

**Comment by rijnhard** [comment]
> I think we can just do this, without flagging for the prior behaviour.

I tend to agree, You are working from a code base anyway, if you removed something and need to re-add it for whatever reason then it's up to your VCS to assist there.
