### ISSUE TITLE
catalog-stats architecture redux

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#891]
## Background

Today, for every tenant in the platform, we create collections `ops/$tenant/stats` and `ops/$tenant/logs`, a derivation `ops/$tenant/catalog-stats` which rolls up metrics drawn from stats and logs, and a materialization `ops/$tenant/catalog-stats-view` which pushes rolled-up stats into a database.

We've realized that there's a data-race which is difficult to solve under this architecture: if TenantA shares a collection `TenantA/Shared` read by `TenantB/Task` and `TenantC/Task`, we produce stat rollups of `TenantA/Shared` which include bytes read from _each_ of the `ops/TenantA/catalog-stats` and `ops/TenantB/catalog-stats` derivations, and their separate materializations go on to race updates of this single rows in the common materialized table.

To fix this, we **MUST** have a single derivation and materialization there-of, which accumulates all stat updates across the platform. This is the only way to guarantee that all stat updates are applied exactly-once to the materialized reporting table.

As a secondary rationale, we've observed that many people register and create tenants in order to tour the product and UI, without immediately setting up tasks and data-flows. They may come back later, but it's likely we'll have a long tail of created tenants that have no tasks or data-flows. It would be nice if we could avoid the cost of a dedicated derivation and materialization for every empty tenant.

We have considered (and rejected) a short-term method by which we could achieve this, which would involve a small amount of runtime support to enable a derivation to dynamically discover and process all per-tenant stat and log journals.

But, having a single derivation & materialization introduces scaling challenges which were less of an issue under the derivation-and-materialization-per-tenant model:

* This single derivation must accumulate statistics across every single `ops/$tenant/stats` and `ops/$tenant/logs` journal in the platform.
* Those collections have potentially _many_ logical partitions, one for each task of the tenant.
* Many tenants will have _no_ logical partitions, most will have just a few, and some will have _lots_.
* Having a single derivation read from an unbounded number of journals is infeasible:
  * Every shard of the derivation must book-keep for all read journals. This book-keeping overhead alone is problematic.
  * Having lots of concurrent reads of cloud-storage fragments can result in slow reads and TCP resets for the individual fragments from the cloud provider.
  * We can't even guarantee that the listing of all such journals will reliably fit in memory!
 * Finally, we plan to remove the current property that a flow reactor is aware of all journals in the system once we introduce federated data-planes.
   * Instead reactors will issue long-lived subscription RPCs to the data-plane of each read collection, to dynamically discover journals.
   * This makes it important that a derivation be able to explicitly name all of the ops stats and logs collections from which it reads.

## Proposal

The solution -- as is often the case -- is another level of indirection: we can scale our stats architecture by introducing multi-stage rollups.

* Tenants would have (only) collections `ops/$tenant/logs` and `ops/$tenant/stats`.

Note that, for a tenant without any tasks, these collections will be empty and will have zero journals (no cost).
The current `/catalog-stats` and `/catalog-stats-view` derivation and materialization would be removed, and users would see only their raw stats and logs collections in their account.

* When a tenant is created, it is assigned to a first-level (L1) rollup derivation like `ops/catalog-stats-L1/0123`.

This would be accomplished by adding a new integer column `L1_stat_rollup` to the `tenants` table, with a default value of 0 (or 1, or 123). We could change this default over time through an `ALTER TABLE` or some other means.

Each such L1 derivation would have many transforms, two for each of its assigned tenants. Specifically, for a tenant `MyTenant`, the derivation has corresponding transforms like `from_MyTenant_logs` and `from_MyTenant_stats`.

This L1 rollup maps granular stats and logs into the hourly / daily / monthly grained stats which we currently use. There would be no required changes to the current function of the rollup.

We would pack a 👋 "reasonable" number of tenants into a single L1 derivation before cutting over to a new and empty L1 derivation (see discussion below).

Collectively, all L1 derivations have a non-overlapping subsets of the total set of platform tenants. A given L1 derivation is responsible for processing all granular stat and log journals only within its subset of tenants.

* A second-level derivation `ops/catalog-stats-L2/0000` would be (for now) the final rollup and derivation.

This derivation would have transforms which read from all L1 derivations. Transforms are the identify function -- the role of the L2 derivation is only to merge and aggregate across L1 derivations.

The naming (`/0000` suffix) leaves open the possibility that we may need to introduce an L3 rollup someday, though that’s hard to foresee.

* A single `estuary/stats-view` materialization would materialize `ops/catalog-stats-L2/0000` into our live reporting table.

This should scale well without further work -- one shard can manage a large number of distinct reporting keys, and we can also split shards as needed to achieve more parallelism.

* We would update mechanisms used for managing various ops specs to be aware of this scheme.

Note that the set of L1 and L2 specs should be a **pure function** of the `tenants` table and our templated ops specs.
When a tenant is created, we'll need to re-generate its assigned L1 derivation spec. This is done, for example, by selecting all _other_ tenants of the assigned L1 spec, to produce its full specification.

However we should **avoid** generating control-plane publications which include _all_ L1 derivation specs, as this is akin to publishing for every single tenant in the platform all-at-once and is certain to not scale well.

## Discussion

In broad strokes, what makes reporting "hard" is that we have a very large number of slow-changing journals which must be continuously read and processed to produce real-time reporting numbers. The mere book-keeping of all of these various journal is the major issue -- especially given our shuffled read machinery that requires every shard of a derivation to book-keep for every read journal. Actual data volumes of these journals is _not_ a problem.

From that perspective, the various L1 and L2 rollups serve to focus a large number of slowly-changing journals into a smaller number of fast-changing journals -- while also achieving significant data reductions along the way (the L1 rollup is likely a ~10x to 100x reduction in overall data volume, for example).

* The L1 rollup reduces N tenant * M task journals into a smallish number of pre-aggregated physical partitions.
* The L2 rollup further reduces the various L1 rollup partitions into a single set of physical partitions, which are then processed by the materialization.

## Scaling

When an L1 derivation is "full", we'll roll new tenants into a next derivation. This notion of "full" is poorly defined: different tenants will have different load levels, and the load of a tenant may change over time as it adds or removes tasks. It's near-certain that different L1 rollups will have different overall loads (both in # of journals read, and overall data volume).

To some extent this is fine: if one L1 derivation is busier than another, we can mitigate by scaling out its shards further than the others.

However we may hit limits in the overall number of read journals which are tricky to overcome, and will likely require future optimization work. **This is work worth doing**, because it directly benefits users that may also want to read from a large number of logical and physical partitions.

### Re-distributing L1 derivations

We may have individual L1 derivations which are _so_ imbalanced that shard splitting is insufficient, we cannot easily optimize them, and we thus wish to break them up and re-distribute their tenants.

There's a pathway to doing this through a possible future feature: supporting `notBefore: $date` and `notAfter: $date` within the `source` stanza of a derivation (or materialization).

If we had such a feature, we could pick a future timepoint $date and then update a "bad" L1 derivation by adding `notAfter: $date` for some some set of tenants. Then, we add those tenants to a _different_ L1 derivation using `notBefore: $date`. So long as $date is in the future with respect to when this change is applied, then we can ensure an atomic cut-over from one L1 derivation to another, while maintaining exactly-once semantics.

### Publication Graph Expansions

We'll need to tweak the graph expansion done at publication time: at present, a given L1 spec's expansion to L2 will then expand back up to all _other_ L1 specs which are transforms of L2, and from there to all of the various ops stats & logs transforms of _those_ L1 specs. This is essentially lumping every tenant in the platform into a single build.

What we can instead do, is include such sibling L1 specs as collections only and remove their `derivation` stanzas (and thus, their transforms) for the purposes of validating the current build.

Having done so, a publication would build over a current complete L1 derivation, the L2 derivation, and collection-only views of all other _sibling_ L1 derivations.

**Comment by williamhbaker** [comment]
Closed via #943
