### ISSUE TITLE
flowctl delete with no arguments attempts to delete all catalogs

### ISSUE THREAD

**Issue by mdibaiee** [estuary/flow#909]
I just noticed that if you do `flowctl catalog delete` with no arguments, it attempts to delete all catalogs, and this can be quite dangerous, specially for admin users.

What do you folks think, should we require at least one filter? @psFried @jshearer

**Comment by psFried** [comment]
OMG! Yeah we should definitely require an argument. Actually it probably even makes sense to require either `--name` or `--prefix`.

**Comment by mdibaiee** [comment]
@psFried I'll send a PR 👍🏽
