### ISSUE TITLE
flowctl catalog publish: message comes after action

### ISSUE THREAD

**Issue by oliviamiannone** [estuary/flow#912]
Using terminal on my M1 mac, OS Monterey.

When I run `flowctl catalog publish`, the message "Enter Y to publish these specs...." doesn't appear with the table of specs to be published:
![image](https://user-images.githubusercontent.com/82397941/216447905-952f0c35-1e56-4ebd-b3a7-17da3a168573.png)

...I actually sat for a while thinking it was working on something, but then I decided to press Enter. Only THEN does the message appear....
<img width="531" alt="image" src="https://user-images.githubusercontent.com/82397941/216448098-445a2075-bd21-438c-b8ba-62098d9c6a06.png">

So now I know because I've been through it that I have to press Y. But again, the message doesn't appear until after I've done so....
<img width="561" alt="image" src="https://user-images.githubusercontent.com/82397941/216448209-3b049142-49bf-4825-b769-4d339b5afad2.png">

**Comment by psFried** [comment]
@oliviamiannone is @mdibaiee is this still happening with the latest release that was published yesterday (`v0.1.8`)? This _should_ have been fixed in #906 (first commit), but would like to confirm that it's working as intended for people other than me :grimacing:

**Comment by oliviamiannone** [comment]
Oop, I hadn't looked at that PR and I filed this issue right before 0.1.8 was released yesterday. Confirmed it's fixed.
