### ISSUE TITLE
Grant Access to demo/ namespace for all tenants

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#921]
**Problem**
We've found that `estuary/public/` isn't quite understood as a namespace and as such would like to create new demos in the `demo/` namespace.  It additionally comes with the benefit of reporting.

**Proposal**
This requires two parts:
 
1. Automatically grant newly created tenants read access to `demo/`
2. Run a query to grant all current tenants read access to `demo/`

**Comment by jgraettinger** [comment]
Done
