### ISSUE TITLE
schemalate: elasticsearch: Error when schema specifies `additionalProperties: false`

### ISSUE THREAD

**Issue by willdonnelly** [estuary/flow#936]
The following example is a minimal reproduction of a bug a user recently encountered:

```
$ flow-schemalate elasticsearch-schema
{ 
  "additionalProperties": false,
  "properties": {
    "foo": { "type": "string" }
  },
  "required": [ "foo" ],
  "type": "object"
}
Error: unsupported Flow schema in elastic search, details: additional properties on an object are not supported, shape: ObjShape { properties: [ObjProperty { name: "foo", is_required: true, shape: Shape { type_: "string", enum_: None, title: None, description: None, reduction: Unset, provenance: Inline, default: None, secret: None, string: StringShape { content_encoding: None, content_type: None, format: None, max_length: None, min_length: 0 }, array: ArrayShape { min: None, max: None, tuple: [], additional: None }, object: ObjShape { properties: [], patterns: [], additional: None } } }], patterns: [], additional: Some(Shape { type_: , enum_: None, title: None, description: None, reduction: Unset, provenance: Inline, default: None, secret: None, string: StringShape { content_encoding: None, content_type: None, format: None, max_length: None, min_length: 0 }, array: ArrayShape { min: None, max: None, tuple: [], additional: None }, object: ObjShape { properties: [], patterns: [], additional: None } }) }
```

As far as I can tell, this specific case isn't intended to be an error and probably stems from a bug in the schema inference crate whereby the presence of the `additionalProperties` clause is misinterpreted? Note that by default in the _absence_ of any `additionalProperties` setting they are permitted.

This is a problem because the schemas generated by SQL capture discovery specify `additionalProperties: false` on the nested object containing source metadata, and so if a user goes down the garden path of capturing from a SQL database and materializing into Elasticsearch they'll get smacked in the face with a really ugly schema translation error message.

I don't recall off the top of my head if there's a reason we *need* to specify `additionalProperties: false` in that part of the discovery output, so if necessary we could revisit that decision, but I'm reasonably sure this is a bug.

**Comment by mdibaiee** [comment]
> I don't recall off the top of my head if there's a reason we need to specify additionalProperties: false in that part of the discovery output, so if necessary we could revisit that decision, but I'm reasonably sure this is a bug.

I can guess that's because elasticsearch will allow additional properties on top of the specified schema by default, but turns out it is possible to disable dynamic mapping, which would be a way of applying `additionalProperties: false`: 

> You can disable dynamic mapping, both at the document and at the [object](https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html) level. Setting the dynamic parameter to false ignores new fields, and strict rejects the document if Elasticsearch encounters an unknown field.

https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html

**Comment by willdonnelly** [comment]
> I can guess that's because elasticsearch will allow additional properties on top of the specified schema by default, but turns out it is possible to disable dynamic mapping, which would be a way of applying additionalProperties: false

I meant that I'm not sure that there's an actual reason that `source-{postgres,mysql,etc}` are specifying `additionalProperties: false` on that specific nested object in the capture output. It seems to me like that's unnecessary in general, and we could probably change things so they don't do that any more if that's the easiest way to resolve the specific problem of "capturing from a SQL database and then materializing to elasticsearch doesn't work".

But I'm pretty sure that would just be sidestepping this bug in the elasticsearch schema translation, which will reoccur in the future as soon as any user has a schema with `additionalProperties: false` in it for other reasons.

**Comment by jgraettinger** [comment]
looking at this i think it's trying to dissuade users from using additionalProperties: { some schema }, not additionalProperties: false, but the check isn't sophisticated enough to distinguish.

I don't understand why we'd want to fail additionalProperties though. It's not failing patternProperties, which is another way of defining schemas over unknown properties...

**Comment by jgraettinger** [comment]
Okay, I pushed a hot-fix for `schemalate` which minimally avoids failing on additionalProperties: false
