### ISSUE TITLE
Improve database support for the billing page

### ISSUE THREAD

**Issue by kiahna-tucker** [estuary/flow#983]
Currently, the UI is pulling the bulk of the data required to populate the views on the _Billing_ page from the `catalog_stats` table. While this provides _some_ necessary information, certain details are missing (e.g., monthly pricing tier evaluations) or indirectly calculated (e.g., entity type/classification).

The information the UI needs to populate views on the _Billing_ page is as follows:

* Task catalog name.

* Task classification (e.g., capture, materialization, or derivation).

* Monthly bytes written and/or read by task.

* Monthly task count by tenant.

* Monthly bytes _processed_ (a.k.a., total data volume) by tenant.

* Pricing tier evaluation by tenant and a record of when a tenant's tier changes.

* Pricing tier constraints (i.e., number of free tasks per month, number of free GB per month, additional task rate, additional GB rate), a record of when the tier constraints are updated, and a record of why the tier constraints were updated (advised, but may be optional).

* Monthly estimated total cost of a Flow subscription by tenant.

## Reference

Issues tracking the development of the _Billing_ page in the UI:

* [515: Create the foundation for a billing page](https://github.com/estuary/ui/issues/515)

**Comment by psFried** [comment]
Just to clarify, my reading of this is that those are all of the things that are required, but only two of them are not already available in `catalog_stats`:


> - Pricing tier evaluation by tenant and a record of when a tenant's tier changes.
> 
> - Pricing tier constraints (i.e., number of free tasks per month, number of free GB per month, additional task rate, additional GB rate), a record of when the tier constraints are updated, and a record of why the tier constraints were updated (advised, but may be optional).

@kiahna-tucker can you confirm whether those are the only things that are missing?

**Comment by psFried** [comment]
Sounds good, thanks. For others following along, we discussed this on a VC and the real issue here is that computing the stats requires further aggregation above and beyond what's done on the `catalog_stats` records. So we want that aggregation to be handled on the server side, to ensure that it's consistent with our actual billing.
